### ISSUE TITLE
ssl.SSLCertVerificationError for batch and streaming starter code of deepgram

### ISSUE THREAD

**Issue by Talha117** [deepgram/deepgram-python-sdk#110]
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

this error appears every time I try to run deepgram batch or streaming starter code

**Comment by keizo** [comment]
is there an ssl bypass for local testing?

**Comment by keizo** [comment]
for anyone having the same issue, /Applications/Python\ 3.11/Install\ Certificates.command worked for me.

**Comment by jpvajda** [comment]
@keizo  thanks for the assistance here @Talha117  could you let us know if this helped resolve your issue?
