### ISSUE TITLE
False language detection

### ISSUE THREAD

**Issue by Mansi9991** [deepgram/deepgram-python-sdk#145]
## Detected language is false
It works fine for language detection in audio file 
but sometimes it detects false language of the audio file..
I've multiple english audio file but for some of them it detects language as hindi and russian for the audio files..

**Comment by lukeocodes** [comment]
Can you provide the request_id of those which were detected incorrectly, and if possible the audio too?

**Comment by Mansi9991** [comment]
```http://52.0.168.209:8001/a6.mp3``` for this audio file the "request_id" is ```14209812-dcee-4e76-b5d3-5def7939367c```
And 
```http://52.0.168.209:8001/a2.mp3``` for this the "request_id" is ```c011def2-0914-484c-8a83-1de1197cf556```

**Comment by jpvajda** [comment]
@Mansi9991  👋  this is probably better posted in our [Community Forum ](https://github.com/orgs/deepgram/discussions)as it sounds like it's not directly related to the SDK. If it's still any issue please post there and our Community can assist.
