### ISSUE TITLE
Deepgram timeouts

### ISSUE THREAD

**Issue by swethmandava** [deepgram/deepgram-python-sdk#151]
`Exception: DG: 408, message='Request Timeout', url=URL('https://api.deepgram.com/v1/listen?smart_format=true&utterances=true&summarize=v2&model=video&diarize=true')`

Worked fine till a few hours ago.

**Comment by SandraRodgers** [comment]
Hi @swethmandava ,

I've just tested this using the Python SDK and I didn't encounter a problem. Can you verify that you were using this Python SDK to make the request? I tested it using the prerecorded example file in the examples folder of this project.

**Comment by swethmandava** [comment]
```
transcript_data = await deepgram.transcription.prerecorded(
        source,
        {
            "smart_format": True,
            "utterances": True,
            "summarize": "v2",
            "model": "video", 
            "diarize": True
        },
    )
```

Yes I'm using the following. It's a large file but I'm able to process other large files without hitting timeouts. it's just this specific file - unsure what's up

**Comment by swethmandava** [comment]
even without timeout = 3000, it fails sometimes for videos of length < 1 hr. what do you recommend?

**Comment by jpvajda** [comment]
@swethmandava timeouts can happen for a lot of reasons but it might all come down to the file size of what you are trying to send to us to transcribe.

so I'd recommend setting the timeout value to `300` seconds (5 minutes) when making a request to Deepgram.

Also I noticed you used our `video` model which part of our Base tier, you can try a few different tier model combinations to see if it performs better. Our newest Nova models are the fastest, so I recommend trying that depending on the language needs of the file.

Here are some Docs that can help you determine a model:

https://developers.deepgram.com/docs/model
https://developers.deepgram.com/docs/models-overview

**Comment by swethmandava** [comment]
I still get timeout errors occasionally. What's the recommended way to retry / upload large files without timeouts?

**Comment by dvonthenen** [comment]
> I still get timeout errors occasionally. What's the recommended way to retry / upload large files without timeouts?

The best way of you are dealing with potential unstable internet connections would be to upload to some publicly accessible S3 bucket and use the transcription via URL method.

**Comment by dvonthenen** [comment]
> I am trying to transcribe an mp3 on my computer of about 1 hour and a half and it keeps timing out. I trying using the parameter timeout = 300 but it said this was invalid syntax. Does anyone know how to fix this?

It's probably because the syntax is invalid (the parameter you are using is not valid). Can you post your code OR how you are calling the function with the parameter declarations here?

**Comment by JoelLederman** [comment]
This is the part of the code that I specify timeout settings: 
options = PrerecordedOptions(
        model="nova",
        smart_format=True,
        summarize="v2",
        diarize=True,
        timeout = 300
    )

**Comment by dvonthenen** [comment]
yea, there isn't a timeout parameter in the transcription options class. it's on the function:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/abstract_sync_client.py#L91-L105

For `transcribe_file` (URL is the same way):
```
myTimeout = httpx.Timeout(30.0, connect=10.0)
response = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options, timeout=myTimeout)
```

**Comment by JoelLederman** [comment]
Ok that worked thanks so much!
Just one more question, the output I get is in this format: =2, speaker_confidence=0.7495117), Word(word='be', start=4066.395, end=4066.635, confidence=1.0, punctuated_word='be', speaker=2, speaker_confidence=0.7495117). 
Is there any way to just get the transcription out as if I was using the API playground. I just want a transcription with speaker diarization as my output.

**Comment by dvonthenen** [comment]
I would understand how dot notation works. Here is an article:
https://builtin.com/data-science/dot-notation#:~:text=Dot%20Notation%20Explained,dot%5D%5Battribute%20or%20method%5D%20.

The structure for what the prerecorded result looks like is here:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/prerecorded/v1/response.py

The Prerecorded Object is *VASTLY* different from the Live Response object, but it might give you a clue on how you want to format your transcription and how to use the dot notation:
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/streaming/microphone/main.py#L34-L37

**Comment by JoelLederman** [comment]
Ok thanks so much you have been an amazing help!

**Comment by osamabinsaleem** [comment]
Hi @dvonthenen @jpvajda  I've this code: 
```
transcription_model = "nova-2-general"
# sometimes we also use "whisper-medium"

with open(audio_efs_path, "rb") as file:
            buffer_data = file.read()

payload: FileSource = {
        "buffer": buffer_data,
}

options = PrerecordedOptions(
                    model=transcription_model,
                    smart_format=True,
                    detect_language=True,
                )
response = deepgram.listen.prerecorded.v("1").transcribe_file(
            payload, options, timeout=httpx.Timeout(300.0, connect=10.0)
        )
```

I've my video files stored on s3 buckets. I first download the file and then I'm converting it to mp3. Then I use the above code to transcibe it. I still occasionally get timeout issues. We get timeout issues with nova-2-general, so model changing doesnt work. 

What do you recommend here: 
1- Re-trying with Exponentional backoff 
2- I should upload the audio to s3 bucket and use the presigned url to get the transcipt 

Thanks!

**Comment by dvonthenen** [comment]
> Hi @dvonthenen @jpvajda I've this code:
> 
> ```
> transcription_model = "nova-2-general"
> # sometimes we also use "whisper-medium"
> 
> with open(audio_efs_path, "rb") as file:
>             buffer_data = file.read()
> 
> payload: FileSource = {
>         "buffer": buffer_data,
> }
> 
> options = PrerecordedOptions(
>                     model=transcription_model,
>                     smart_format=True,
>                     detect_language=True,
>                 )
> response = deepgram.listen.prerecorded.v("1").transcribe_file(
>             payload, options, timeout=httpx.Timeout(300.0, connect=10.0)
>         )
> ```
> 
> I've my video files stored on s3 buckets. I first download the file and then I'm converting it to mp3. Then I use the above code to transcibe it. I still occasionally get timeout issues. We get timeout issues with nova-2-general, so model changing doesnt work.
> 
> What do you recommend here: 1- Re-trying with Exponentional backoff 2- I should upload the audio to s3 bucket and use the presigned url to get the transcipt
> 
> Thanks!

I think this is answered here:
https://github.com/deepgram/deepgram-python-sdk/issues/423

**Comment by Hercilio1** [comment]
@davidvonthenen , that's not the case. The problem is that even after increasing the timeout, the timeout error occasionally happens again. Even though some `speech_to_text.transcribe_file` executions take ~20 seconds to run, occasionally they are not downloaded even within 5 minutes.  

I tested the API (`deepgram.listen.prerecorded.v("1").transcribe_file`) with a 5MB file, and it transcribes it in 2 seconds. Occasionally (1 in 3 executions), it takes 30 seconds. What I'm assuming is that 1 in 3 times, the DeepGram API takes significantly longer to transcribe videos/audios. For a 30MB file, 5 minutes is not enough, and I don't think increasing the timeout to 1 hour would be the proper solution.
