### ISSUE TITLE
Balance deduction in summary report 

### ISSUE THREAD

**Issue by akjoshi009** [deepgram/deepgram-python-sdk#153]
## Proposed changes

> Summarize Usage api returns following details 
end,start,requests,hours

but we dont understand the daily how much we spend ?
so please add how much money we get charged for that day for total requests or total minutes

**Comment by jkroll-deepgram** [comment]
Hi @akjoshi009, cost is not included in the Summarize Usage API. You can use the Get All Requests API (with an optional start and end date range) for your Deepgram project, and then take the sum of all requests' costs.

Check out this thread sharing a Python script that you can adapt to get started quickly: https://github.com/orgs/deepgram/discussions/240#discussioncomment-7145359
