### ISSUE TITLE
Typing in _type.py is out of date with what is actually returned from API

### ISSUE THREAD

**Issue by will-btrt** [deepgram/deepgram-python-sdk#157]
## What is the current behavior?

the types in _types.py don't actually represent what is returned from the API. Specifically I am using the Paragraphs feature, and the API returns `paragraphs.paragraphs.speaker` which I would like to access, but the typing does not list the speaker as a field (which is optionally there if you specify diarization).

## Steps to reproduce

- Use the Python SDK
- Specify Smart formatting and Diarization
- Transcribe something
- Use typing
- Try access the the speaker field from within the paragraphs and your typing will complain because the SDK doesn't actually contain the possible fields returned from the API.

## Expected behavior

I would expect to see `speaker: Optional[int]` [here](https://github.com/deepgram/deepgram-python-sdk/blob/0899ff9c10b3fc82c5bd92401924a133aeb6526b/deepgram/_types.py#L185C1-L185C1)

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** macOS 12.5.1
- **Language:** Python
- **Browser:** Chrome

## Other information

`deepgram-sdk==2.11.0`

**Comment by dvonthenen** [comment]
This should be fixed in this PR
https://github.com/deepgram/deepgram-python-sdk/pull/177

**Comment by dvonthenen** [comment]
This should be addressed in the latest PR. You can either check using main branch or wait for the next published release.
