### ISSUE TITLE
Include webvtt and srt formatting

### ISSUE THREAD

**Issue by SandraRodgers** [deepgram/deepgram-python-sdk#159]
## Proposed changes

Provide methods to transform  a Deepgram prerecorded transcription response into WebVTT or SRT captions
**We've decided to do this as a separate package**

## Context

This feature was available in V2 as `to_WebVTT()` or `.to_SRT()`. We need to continue to provide this feature in V3

## Possible Implementation

See V2 implementation: https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/extra.py

Take this V2 implementation and create a standalone python package to create captions. The standalone package can be a dependency in this SDK so users can use it from the SDK, or they can use it independently.

**Comment by jpvajda** [comment]
@SandraRodgers is this considered done since we released the python caption package?

**Comment by SandraRodgers** [comment]
Not done because we still need to add it as a dependency so it can be used in the SDK @jpvajda

**Comment by dvonthenen** [comment]
@SandraRodgers I'm assuming this is no longer needed since we have the captions library/repo now.

**Comment by dvonthenen** [comment]
For those that are interested, please checkout this project:
https://github.com/deepgram/deepgram-python-captions/tree/main
