### ISSUE TITLE
Update the setup.py file

### ISSUE THREAD

**Issue by SandraRodgers** [deepgram/deepgram-python-sdk#160]
## Proposed changes

The setup.py file is out of date. It needs to be updated for this new version release.

## Context

We have changed some of the dependencies, such as using `httpx` instead of `aiohttp` to make http requests. The author is also out of date. Basically, this needs a possible rewrite due to the significant number of changes we are making for v3.

## Possible Implementation

Research what is needed in a setup.py file and make appropriate changes.

## Other information

Need to consider the version - this needs to stay in sync as the SDK is updated.

**Comment by dvonthenen** [comment]
This should be fixed in this PR
https://github.com/deepgram/deepgram-python-sdk/pull/172

**Comment by dvonthenen** [comment]
updated in this PR:
https://github.com/deepgram/deepgram-python-sdk/pull/182

**Comment by dvonthenen** [comment]
This PR should address the requirements updates. All dependencies are contained at the root of the repo.
https://github.com/deepgram/deepgram-python-sdk/pull/182
