### ISSUE TITLE
Summarize (Read) supported 

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-python-sdk#163]
* new param `summarize` added for summarization for `/read` requests.

**Comment by dvonthenen** [comment]
implemented here:
https://github.com/dvonthenen/deepgram-python-sdk/tree/feature-sits-impl

it should all be working in that branch including examples

**Comment by dvonthenen** [comment]
PR Merged. Will be available on the next release (today or tomorrow-ish).
