### ISSUE TITLE
Sentiment (Read) supported

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-python-sdk#168]
* new param `sentiment` added for sentiment analysis for `/read` requests.

**Comment by UniversalDevGenius** [comment]
@jpvajda I would like to work on this issue, can you provide more context regarding it.

**Comment by dvonthenen** [comment]
@UniversalDevGenius You missed it by about a day... it's already implemented here:
https://github.com/dvonthenen/deepgram-python-sdk/tree/feature-sits-impl

Just need to rename a couple of functions after discussing what they should be called.

**Comment by dvonthenen** [comment]
it should all be working in that branch including examples

**Comment by dvonthenen** [comment]
PR Merged. Will be available on the next release (today or tomorrow-ish).
