### ISSUE TITLE
Sentiment (Listen) supported

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-python-sdk#169]
* old param `analyze_sentiment` should be kept for backwards compatibility cases. 
* new param `sentiment` added for sentiment analysis  for `/listen` requests.

**Comment by UniversalDevGenius** [comment]
@jpvajda I would like to work on this issue, can you provide more context regarding it.

**Comment by dvonthenen** [comment]
@UniversalDevGenius You missed it by about a day... it's already implemented here:
https://github.com/dvonthenen/deepgram-python-sdk/tree/feature-sits-impl

Just need to rename a couple of functions after discussing what they should be called.

**Comment by dvonthenen** [comment]
it should all be working in that branch including examples

**Comment by UniversalDevGenius** [comment]
> @UniversalDevGenius You missed it by about a day... it's already implemented here: https://github.com/dvonthenen/deepgram-python-sdk/tree/feature-sits-impl
> 
> Just need to rename a couple of functions after discussing what they should be called.

@dvonthenen Can you share me some issues that I can contribute just tag them here or assign them to me, I really appreciate if you give me an chance to work on interesting issue to start mine first every open source contribution.

**Comment by dvonthenen** [comment]
PR Merged. Will be available on the next release (today or tomorrow-ish).
