### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by jeckyP** [deepgram/deepgram-python-sdk#171]
The readme example has 
```
        response = deepgram.transcription.sync_prerecorded(source, {'punctuate': True})
```

And there is no mention of `sync_prerecorded()` in the docs (I believe this would be the place? https://developers.deepgram.com/docs/getting-started-with-pre-recorded-audio)

**Comment by jpvajda** [comment]
@jeckyP thanks for pointing this out. We are actually working on a major release for the Python SDK where we'll be rewriting a lot of the Readme documentation.  @dvonthenen  👋

**Comment by dvonthenen** [comment]
@jeckyP will make sure this gets addressed when the docd get rewritten!

**Comment by dvonthenen** [comment]
Focusing on clean up, documentations, spelling, etc for v3. Will take a look at this.

**Comment by dvonthenen** [comment]
This should be addressed in this PR:
https://github.com/deepgram/deepgram-python-sdk/pull/209

**Comment by dvonthenen** [comment]
If there is still an outstanding issue, please let me know!
