### ISSUE TITLE
Use `dataclasses_json` for `dataclasses`

### ISSUE THREAD

**Issue by dvonthenen** [deepgram/deepgram-python-sdk#180]
## Proposed changes

Reported by @jjmaldonis:
Can we use dataclasses rather than TypedDicts? The syntax is very similar but the functionality is much better. If we use dataclasses, we can decorate them with [dataclasses_json](https://github.com/lidatong/dataclasses-json) to make it easy to convert to/from dictionaries/json.

## Context

NA

## Possible Implementation

NA

## Other information

NA

**Comment by dvonthenen** [comment]
This PR addresses this particular issue and also maintains the backwards compatibility of using `TypedDict` access (ie using key/value pairs).
https://github.com/deepgram/deepgram-python-sdk/pull/182

If it doesn't, we can reopen to investigate.

**Comment by jjmaldonis** [comment]
I must be missing something - is there a PR that added dataclasses to the repo?

#182 got merged into `main` but I don't see any use of dataclasses on the `main` branch. Same with issue #181.
