### ISSUE TITLE
3.0.0a4 poetry install seems to be missing files from egg

### ISSUE THREAD

**Issue by cstigler** [deepgram/deepgram-python-sdk#196]
## What is the current behavior?

Installing the new 3.0.0a4 build is failing for me (the previous 2.x builds worked fine). Specifically, after installing and trying to run I see this error:

```
2023-12-01 00:55:43   File "/usr/local/lib/python3.11/site-packages/deepgram/client.py", line 8, in <module>
2023-12-01 00:55:43     from .clients.listen import ListenClient
2023-12-01 00:55:43 ModuleNotFoundError: No module named 'deepgram.clients'
```

And indeed, when I look at the installed package directory, it seems to be missing most of its folders, including the clients folder:

```
(dev-py3.11) (base) charlie@Charliebook deepgram % ls
__init__.py	client.py	errors.py	options.py
```

It looks like for some reason most of the actual code isn't making it into the egg that's being installed.

## Steps to reproduce

1. Add deepgram 3.0.0a4 to pyproject.toml
2. Run `poetry lock` and then `poetry install`
3. Attempt to run the application

## Expected behavior

It would work properly because all required files would be there.

## Please tell us about your environment
  
- **Operating System/Version:** macOS 14.0
- **Language:** Python
- **Browser:** Chrome

**Comment by dvonthenen** [comment]
Thanks for filing the issue @cstigler . Will take a look!

**Comment by ohharsen** [comment]
@dvonthenen I am getting it on alpha.5 as well

**Comment by ohharsen** [comment]
@dvonthenen Works on rc.2!

**Comment by dvonthenen** [comment]
> @dvonthenen Works on rc.2!

Sweet! Thanks! Glad it's working!
