### ISSUE TITLE
The diarization is allowed in SPANISH but always identifies user with id 0

### ISSUE THREAD

**Issue by furo-ops** [deepgram/deepgram-python-sdk#203]
## What is the current behavior?
I was expecting a differential behavior in terms of STT with a good diarization to differentiate agent from user and be able to work out on my end the different interactions but always identifies the user with ID: 0 in SPANISH

## Steps to reproduce

This is my api call:
```python
api_key = 'api_key'
file_path = 'audio.mp3'
language_option = 'es'

url = f'https://api.deepgram.com/v1/listen?model=general&tier=nova&version=latest&language=es&detect_language=false&punctuate=true&redact=true&diarize=true&smart_format=true&filler_words=true&multichannel=false&utterances=true'

headers = {
    'Authorization': f'Token {api_key}'
}

# Preparing the multipart/form-data request
with open(file_path, 'rb') as file:
   response = requests.post(url, headers=headers, data=file)

print(response.text)
```

## Expected behavior

The expected behavior was to dentify all the speakers differently but identifies all of them as user:0

## Please tell us about your environment
Runninng on python 3.11.2 and followed all the docs indications.

Am I missing something?

**Comment by jkroll-deepgram** [comment]
Hi @furo-ops, I don't believe you're doing anything incorrectly. This is a known issue that can occur with certain combinations of audio and models. It can be due to a variety of factors and edge cases. Are you able to share any Deepgram request IDs from API calls that are returning diarized transcripts showing all Speaker 0? For reference, you can find request IDs in the JSON response under `response["metadata"]["request_id"]`.

**Comment by furo-ops** [comment]
Good morning :)
Thank you for your fast reply! 
The request_id is the following: 
```json
{"request_id":"ed97ae12-fad4-4150-9bb6-b0f0bf99fb96"}
```

**Comment by jkroll-deepgram** [comment]
Thanks for sharing the request ID! I've started taking a look and unfortunately don't have any fast recommendations for this particular audio. My broad suggestion is to test a few different audio files as performance may not be representative with just one file. I'll look further and see if I can find anything else to boost accuracy in your specific case.

**Comment by dvonthenen** [comment]
hi @furo-ops have you been able to check out other audio sources?

**Comment by furo-ops** [comment]
I'm testing with some other audio files, I'll let you know if I am able to retrieve correctly the speakers' id :)

**Comment by dvonthenen** [comment]
If you run into any issues, please reach out here (you can reopen) or in Discord.

**Comment by furo-ops** [comment]
Seems like the problem is solved now, diarization returns correctly the speakers now in spanish. Great update, congratulations!
