### ISSUE TITLE
Realtime Transcription using synchronous approach

### ISSUE THREAD

**Issue by shrimad-mishra-cognoai** [deepgram/deepgram-python-sdk#210]
Hi there,

I am currently using the Python SDK for realtime transcribing. I saw that the SDK implementation is done using the async approach. However, I need a way in which I can achieve real-time transcribing in a sync approach. 

I want in sync approach because my complete wss logic is implemented in a sync way itself.

Is it possible with the deepgram?

**Comment by jjmaldonis** [comment]
Hey @shrimad-mishra-cognoai, does this example cover the use case you're looking for? If not, can you explain more?

https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/streaming/http/main.py

**Comment by shrimad-mishra-cognoai** [comment]
In which deepgram version it is present or can you let me know the python library for this I have installed deepgram-sdk

**Comment by dvonthenen** [comment]
The best way is to install the v3 RC is:
`pip install deepgram-sdk==3.0.0-rc.1`

**Comment by shrimad-mishra-cognoai** [comment]
Thanks for the help.

Getting this error
**[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)**
I have set the Deepgram API key in the environment

**Comment by dvonthenen** [comment]
> Thanks for the help.
> 
> Getting this error **[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)** I have set the Deepgram API key in the environment

If you're using macOS go to Macintosh HD > Applications > Python3.11 folder (or whatever version of python you're using) > double click on "Install Certificates.command" file.

**Comment by shrimad-mishra-cognoai** [comment]
Getting this error continuously

Exception in _listening: received 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001; then sent 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001

**Comment by dvonthenen** [comment]
Are you trying to run an example? or your own code? If you are running your own code, if you can link to it that would be helpful. Otherwise, if the code isn't open, we can do over DM in Discord.

**Comment by shrimad-mishra-cognoai** [comment]
Can you provide the discord ID will share the code with you over ther

**Comment by dvonthenen** [comment]
You can join discord here:
https://dpgr.am/discord

**Comment by shrimad-mishra-cognoai** [comment]
Hi can you please provide the same for the async

**Comment by dvonthenen** [comment]
> Hi can you please provide the same for the async

I'm not sure you messaged in Discord, but I am going to need more information in order to help you debug your problem. If you don't mind sharing some info/code here or over Discord DM, that would be helpful.

**Comment by dvonthenen** [comment]
I haven't heard back. If you are still having issues, please reopen.
