### ISSUE TITLE
Version 3.0.0 Upgrade Guide?

### ISSUE THREAD

**Issue by SishaarRao** [deepgram/deepgram-python-sdk#217]
Will a 3.0.0 upgrade guide be published?

**Comment by dvonthenen** [comment]
Hi @SishaarRao I will pull something together next week that will map 1-to-1 functionality from v2 to v3.

**Comment by dvonthenen** [comment]
Hi @SishaarRao 

You can find a migration guide here:
https://developers.deepgram.com/docs/javascript-sdk-v2-to-v3-migration-guide-copy
