### ISSUE TITLE
Documentation not matching at the official website

### ISSUE THREAD

**Issue by Kedar-dave** [deepgram/deepgram-python-sdk#219]
It looks like the official documentation of Deepgram API usage [https://developers.deepgram.com/docs](url) is not updated to the latest version of the API. Please check the content.

**Comment by dvonthenen** [comment]
This should be fixed now.

Pre-recorded:
https://developers.deepgram.com/docs/python-sdk-pre-recorded-transcription

Live:
https://developers.deepgram.com/docs/python-sdk-streaming-transcription

If you have any issues with the official documentations, please let me know. Feedback is welcome!

**Comment by Kedar-dave** [comment]
Thanks for the Update!
