### ISSUE TITLE
attempting transcribe of prerecorded file with python

### ISSUE THREAD

**Issue by llorban** [deepgram/deepgram-python-sdk#222]
Trying to work with, examples/prerecorded/file/main.py

lands on this error: 

```
Traceback (most recent call last):
  File "/Users/llorban/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Recordings of Focus Group/main.py", line 5, in <module>
    from deepgram import (
  File "/opt/homebrew/lib/python3.9/site-packages/deepgram/__init__.py", line 9, in <module>
    from .client import DeepgramClient
  File "/opt/homebrew/lib/python3.9/site-packages/deepgram/client.py", line 125
    match self.parent:
          ^

```

Running python3.9, pip 23.3.2, deepgram-sdk 3.0.0

**Comment by dvonthenen** [comment]
I have not tried 3.9 myself. The minimum I have tested with and also that we are claiming to support in v3 is python 3.10. Try upgrading your python version.

**Comment by llorban** [comment]
Thank you - yes, a new version of python seems to have resolved the issue. Somewhere on the deepgram website 3.7+ is suggested.

**Comment by dvonthenen** [comment]
> Thank you - yes, a new version of python seems to have resolved the issue. Somewhere on the deepgram website 3.7+ is suggested.

Glad you got it working. As of `v3` release published this week, the minimum supported version is python 3.10.
