### ISSUE TITLE
Deepgram Async Python is not working 

### ISSUE THREAD

**Issue by kj3moraes** [deepgram/deepgram-python-sdk#225]
## What is the current behavior?

I have followed the Deepgram Django tutorial and have implemented a Django app to perform transcription, however Deepgram sends null transcripts back even though the log on my Deepgram console says that its a 101 OK. I get these responses when I print the results from the Deepgram API

```
LiveResultResponse(type='Results', channel_index=[0, 1], duration=3.26, start=0.0, is_final=True, speech_final=False, 
channel=Channel(alternatives=[Alternative(transcript='', confidence=0.0, words=[])]), metadata=Metadata(request_id='...', 
model_info=ModelInfo(name='general-nova', version='2023-07-06.22746', arch='nova'), model_uuid='aa274f3c-e8b3-456a-ac08-dfd797d45514'))
```

As you can see there is not transcript. 

## Steps to reproduce

My consumers.py file is below. This has changed the most because the Django tutorial is out of data. The rest is the same as the tutorial [here](https://github.com/deepgram/deepgram-python-sdk/).  

## Expected behavior

Ideally, I should be getting the transcription back. I have tried 
- saving the bytes passed over the socket as an .wav audio file. (the audio is correct and audible, no static)

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** Fedora 35.0
- **Language:** Python 3.10
- **Browser:** Firefox 107.0

## Other information

The following is a Loom walkthrough of the entire problem. 

[Demo-ty issue with audio transcription - Watch Video](https://www.loom.com/share/0c8b4ca154d14d468426d5cf7ede0149)

The following is my consumers.py file 
```python3
from channels.generic.websocket import AsyncWebsocketConsumer
from dotenv import load_dotenv
from deepgram import DeepgramClient, LiveOptions, LiveTranscriptionEvents
from django.conf import settings
import os

load_dotenv()
DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")


# Callback function for REGULAR MESSAGES
def on_message(self, result, **kwargs):
    print("\t\tCallback here")
    if result is None:
        print("\t\tResult is None")
        return
    print(result)
    sentence = result.channel.alternatives[0].transcript
    if len(sentence) == 0:
        print("\t\tSentence is is None")
        return
    print(f"Transcription: {sentence}")

# Callback function for ERRORS
def on_error(self, error, **kwargs):
    if error is None:
        return
    print(f"\n\nERROR:\n{error}\n\n")

class TranscriptConsumer(AsyncWebsocketConsumer):
    
    async def connect(self):
        self.counter = 1
        self.dg_client = DeepgramClient()
        self.dg_conn = self.dg_client.listen.asynclive.v("1")
        self.options = LiveOptions(
            model="nova",
            punctuate=True,
            language="en-US",
            encoding="linear16",
            channels=1,
            sample_rate=16000,
        )

        self.dg_conn.on(LiveTranscriptionEvents.Transcript, on_message)
        self.dg_conn.on(LiveTranscriptionEvents.Error, on_error)
        await self.dg_conn.start(self.options)
        await self.accept()
        print("Accepted connection")

    async def disconnect(self, close_code):
        print("Disconnecting")
        self.close(close_code)
        self.dg_conn.finish()

    async def receive(self, text_data=None, bytes_data=None):
        print("Received data for transcriptions")
        if bytes_data is not None:
            print("Sending to the socket")
            self.counter += 1
            path_to_audio = f"{settings.AUDIO_SAVE_DIR}/audio{self.counter}.wav"
            await self.dg_conn.send(bytes_data)
```

My index.html file is below
```
<!DOCTYPE html>
<html>
    <head>
        <title>Chat</title>
    </head>
    <body>
        <h1>Transcribe Audio With Django</h1>
        <p id="status">Connection status will go here</p>
        <p id="transcript"></p>
       
        <script>
           navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
            if (!MediaRecorder.isTypeSupported('audio/webm'))
                return alert('Browser not supported')

            const mediaRecorder = new MediaRecorder(stream, {
                mimeType: 'audio/webm',
            })
             
            const socket = new WebSocket('ws://localhost:8000/listen')

            socket.onopen = () => {
                document.querySelector('#status').textContent = 'Connected'
                console.log({ event: 'onopen' })
                mediaRecorder.addEventListener('dataavailable', async (event) => {
                    if (event.data.size > 0 && socket.readyState == 1) {
                        console.log("Sending data over to socket")
                        socket.send(event.data)
                    }
                })
                mediaRecorder.start(5000)
            }

            socket.onmessage = (message) => {
                const received = message.data
                if (received) {
                    console.log(received)
                    document.querySelector('#transcript').textContent += ' ' + received
                }
            }

            socket.onclose = () => {
                console.log({ event: 'onclose' })
            }

            socket.onerror = (error) => {
                console.error({ event: 'onerror', error })
            }

            })

        </script>
    </body>
</html>
```

**Comment by dvonthenen** [comment]
Hi @kj3moraes 

Let's start with the async example in the repo (below). Does that work for you when you run it?
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/streaming/async_http/main.py

If so, I am curious as to what the `await self.accept()` and `self.close(close_code)` does?

Also In the code below, the `receive()` function appears to be sending audio to Deepgram platform and the function name is just awkwardly named because the function doesn't actually "receive" any audio or data. In other words, who is calling this `receive()` function?
```
    async def receive(self, text_data=None, bytes_data=None):
        print("Received data for transcriptions")
        if bytes_data is not None:
            print("Sending to the socket")
            self.counter += 1
            path_to_audio = f"{settings.AUDIO_SAVE_DIR}/audio{self.counter}.wav"
            await self.dg_conn.send(bytes_data)
```

**Comment by kj3moraes** [comment]
Hello @dvonthenen 

Thanks for the reply. Yes, linked example works perfectly when I run it. 

Since I am using Django channels, the `self.accept()` accepts the WebSocket connection and the `self.close(close_code)` terminates the connection. 
The `recieve(text_data, bytes_data)` is a standard in Django channels for receiving data from a client that has established the connection with the server. 

My envisioned goal with this:
1. A client connects to the server via the specified URL 
2. The client sends audio data as bytes to the server (this app)
3. The server app uses Deepgram to get the transcript asynchronously
4. The server app then async sends the transcript of the audio snippet to the client and continuously appends it to a file.

**Comment by dvonthenen** [comment]
Ok. I just noticed the loom video you have... I'm assuming the web interface connection is connecting to this python backend, I am guessing that the problem is the encoding is not correct. You technically are using the microphone (which is why I can see you are using "linear16"), but in reality, you are using some web framework representation of a microphone which is probably not sending data in a "linear16" format. Not sure what framework you are using, but if you answer that question and then adjust the encoding in the python code, it should work.

**Comment by kj3moraes** [comment]
Hello @dvonthenen 

Thanks a lot of this. All it took was removing "linear16" from the encoding and it worked after that.

**Comment by kj3moraes** [comment]
This is now resolved.
