### ISSUE TITLE
AsyncLive with `async` `on_transcript`, `on_metadata`, `on_error` etc functions capability?

### ISSUE THREAD

**Issue by PuneetGrov3r** [deepgram/deepgram-python-sdk#226]
## What is the current behavior?
Currently `asynclive.v("1")`  works with sync `on_transcript` etc functions and async functions gives not awaited error. 

For a overall async application, wouldn't it make more sense to keep these hooks to be async? it's giving us a hard time working with both sync and async code because of this. 

## Please tell us about your environment
  
- **Operating System/Version:** Amazon Linux 2023
- **Language:** [Python]

## Other information

Can you add a check in `deepgram/clients/live/v1/async_client.py` file on line no. 83 and check if handler is a coroutine or not using `inspect.iscoroutinefunction` function? Why was it not done like this before, is there a reason for this?

**Comment by dvonthenen** [comment]
This looks like a bug. The callback functions should be `async` as you pointed out.

**Comment by dvonthenen** [comment]
Hi @PuneetGrov3r 

Please take a look at https://github.com/deepgram/deepgram-python-sdk/pull/227 and see if that addresses your issue.

**Comment by PuneetGrov3r** [comment]
great, I think it solves the issue.

**Comment by dvonthenen** [comment]
PR merged. Closing.
