### ISSUE TITLE
Django Channels Websocket with Callbacks

### ISSUE THREAD

**Issue by kj3moraes** [deepgram/deepgram-python-sdk#235]
## Context

I have an `AsyncWebsocketConsumer` in Django and I want to receive audio data (as bytes) from a frontend, transcribe it asycn with Deepgram and send it back to the frontend through the same Websocket connection.  

I have gone through the Django-Deepgram tutorial. Unfortunately it is out of date because it is for the old SDK version, so I ported over the implementation with the new SDK. 

## Current Problem

The current problem I have is in the `custom_transcription_file` function below. The objective is :- 
- The frontend establishes a connection (sends some text data like the name of the person and the date)
- The backend makes a custom file to store the transcript in and _prepares to send the transcript back to the frontend_
- The frontend sends audio bytes and the backend sends back the transcription text data __and__ stores the transcript in the designated text file.
 
### Other information

My `consumers.py` file 

```python
from channels.generic.websocket import AsyncWebsocketConsumer
from dotenv import load_dotenv
from deepgram import DeepgramClient, LiveOptions, LiveTranscriptionEvents
from django.conf import settings
import os
import json

load_dotenv()
DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")

def custom_transcription_file(name: str, date: str, **kwargs):

    transcript_dir = settings.TRANSCRIPTS_SAVE_PATH / date
    transcript_dir.mkdir(exist_ok=True)

    send_fn = kwargs["send_fn"]
    # TODO: Check that the send function is a callable

    transcript_file_name = transcript_dir / f"{name}.txt"
    with open(transcript_file_name, "w+") as outfile:
        outfile.write(f"=== CONVERSATION TRANSCRIPT WITH {name} ===\n\n")

    # Callback function for REGULAR MESSAGES
    def on_message(self, result, **kwargs):
        if result is None:
            return
        sentence = result.channel.alternatives[0].transcript
        if len(sentence) == 0:
            return

        # Print the transcript
        print("TRANSCRIPT: ", sentence)

        # Save the transcript to a file
        with open(transcript_file_name, "a") as outfile:
            outfile.write(f"You: {sentence}\n")

        # Send the transcript via the websocket connection to the frontend
        send_fn(text_data=json.dumps({"transcript": sentence}))
    
    return on_message 


class TranscriptConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        self.dg_client = DeepgramClient()
        self.dg_conn = self.dg_client.listen.asynclive.v("1")
        self.options = LiveOptions(
            model="nova",
            punctuate=True,
            language="en-US",
            channels=1,
            sample_rate=16000,
        )
        await self.dg_conn.start(self.options)
        await self.accept()
        print("Accepted connection")

    async def disconnect(self, close_code):
        print("Disconnecting")
        self.close(close_code)
        self.dg_conn.finish()

    async def receive(self, text_data=None, bytes_data=None):
        # This only happens at the start of a connection when
        # we have to send some metadata information like the name
        # of the person and the time.
        if text_data is not None:
            print("TEXT DATA RECEIVED ", text_data)
            info_dict = json.loads(text_data)
            name = info_dict.get("name")
            if name is None:
                return

            # We are expecting date of the form DD_MM_YYYY (with no spaces)
            date = info_dict.get("date")
            if date is None:
                return
            self.name = name
            self.date = date

            # Register the callbacks for all the transcripts.
            transcript_callback = custom_transcription_file(
                self.name, self.date, send_fn=self.send
            )
            self.dg_conn.on(
                LiveTranscriptionEvents.Transcript,
                transcript_callback
            )
            # TODO: Register callbacks for errors, utterances and metadata.

        if bytes_data is not None:
            await self.dg_conn.send(bytes_data)

```

My `index.html` file
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Chat</title>
    </head>
    <body>
        <h1>Transcribe Audio With Django</h1>
        <p id="status">Connection status will go here</p>
        <p id="transcript"></p>
       
        <script>
           navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
            if (!MediaRecorder.isTypeSupported('audio/webm'))
                return alert('Browser not supported')

            const mediaRecorder = new MediaRecorder(stream, {
                mimeType: 'audio/webm',
            })
            
            
            const date = new Date();
            let day = date.getDate();
            let month = date.getMonth() + 1;
            let year = date.getFullYear();

            // This arrangement can be altered based on how we want the date's format to appear.
            let currentDate = `${day}_${month}_${year}`;

            var socket = new WebSocket('ws://localhost:8000/listen')
            
            socket.onopen = () => {
                socket.send(JSON.stringify({"name": "Keane", "date": currentDate}));
                document.querySelector('#status').textContent = 'Connected'
                console.log({ event: 'onopen' })
                mediaRecorder.addEventListener('dataavailable', async (event) => {
                    if (event.data.size > 0 && socket.readyState == 1) {
                        console.log("Sending data over to socket")
                        socket.send(event.data)
                    }
                })
                mediaRecorder.start(500)
            }

            socket.onmessage = (message) => {
                console.log("received data from websocket")
                const received = message.data
                console.log("recieved ", received)
                if (received) {
                    console.log(received)
                    document.querySelector('#transcript').textContent += ' ' + received
                }
            }

            socket.onclose = () => {
                console.log({ event: 'onclose' })
            }

            socket.onerror = (error) => {
                console.error({ event: 'onerror', error })
            }

            })

        </script>
    </body>
</html>
```

## What I need help in ?

- How do I make a callback function to Deepgram that will send the trancript back via the Websocket connection I have setup ?

Any help will be appreciated thanks.

**Comment by dvonthenen** [comment]
Hi @kj3moraes 

You might want to take a look at this first before implementing anything
https://developers.deepgram.com/docs/callback

**Comment by dvonthenen** [comment]
Seems like you have an issue with connection between the UI and this backend component. I have a feeling that your `send_fn` might be blocking. I bet if you put a print statement after the send, you probably never end up seeing it.

**Comment by kj3moraes** [comment]
Hey @dvonthenen ,

I don't think it is the send_fn because I am inheriting from Django's AsyncWebsocketConsumer and its send function is async as defined [here](https://github.com/django/channels/blob/a6d7f71c3332edeced1cc012de2ed020a7932ae5/channels/generic/websocket.py#L204). 

I tried putting the print function after the `send_fn` and it managed to print out the statement. The code and the log are below

```python
    # Callback function for REGULAR MESSAGES
    def on_message(self, result, **kwargs):
        if result is None:
            return
        sentence = result.channel.alternatives[0].transcript
        if len(sentence) == 0:
            return

        # Print the transcript
        print("TRANSCRIPT: ", sentence)

        # Save the transcript to a file
        with open(transcript_file_name, "a") as outfile:
            outfile.write(f"You: {sentence}\n")

        # Send the transcript via the websocket connection to the frontend
        send_fn(text_data=json.dumps({"transcript": sentence}))
        print("Attempting to check blocking")
```

```
HTTP GET /api/transcript/index.html 200 [0.01, 127.0.0.1:60312]
WebSocket HANDSHAKING /listen [127.0.0.1:60320]
WebSocket CONNECT /listen [127.0.0.1:60320]
Accepted connection
TEXT DATA RECEIVED  {"name":"Keane","date":"4_1_2024"}
TRANSCRIPT:  Alright.
Attempting to check blocking
TRANSCRIPT:  You have connected
Attempting to check blocking
TRANSCRIPT:  and
Attempting to check blocking
```
(Console on broswer)
![Screenshot_20240104_084714](https://github.com/deepgram/deepgram-python-sdk/assets/25700338/82112faf-b44c-44c6-a90d-09a7ac9d00f9)


I don't think I can change the send function because it is an inherited method. I can override it however but I am not sure how that would integrate with the Deepgram callback. Do you have any suggestions for this ?

**Comment by dvonthenen** [comment]
I just noticed that you are using the async client. You need async awaits on your call back functions and also on your send function. 

Please see the example below
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/streaming/async_http/main.py

**Comment by kj3moraes** [comment]
Hello @dvonthenen 

Making `on_message` async and prepending await to `send_fn` does not work unfortunately. It simply won't send anything and now won't even write to the file. 

I saw the example that you listed and in that `on_message` was async and I tried to do it that way but the aforementioned problem still stands. I don't believe it is a problem with the `index.html` file either because I am console logging any message the server sends back and the server does not send anything back - neither in the current implementation nor with async and await for the `on_message` and `send_fn`.

**Comment by dvonthenen** [comment]
So I am trying to understand this, it looks like from the above logging you are getting the transcription back from deepgram?
```
TRANSCRIPT:  Alright.
Attempting to check blocking
TRANSCRIPT:  You have connected
Attempting to check blocking
TRANSCRIPT:  and
Attempting to check blocking
```

What is exactly the problem then?

**Comment by kj3moraes** [comment]
Yes, but I want to send the these transcript sentences back to the client via the Websocket connection. I made a `send_fn` for this but the client receives no data. 

I need to send data back to the client using the same websocket connection. Is there any workaround for this in the callback mechanism.

**Comment by dvonthenen** [comment]
ok, so there isnt a problem with SDK and the transcription is working just fine.

You might need to debug your code then. can you put print statements inside your `send_fn` function?

- first, if it's actually getting called, like first on enter...
```
de myFunc(data):
    print("enter...")
    // so on...
``` 
- then print statements between key statements to see where it is falling apart inside your function.
```
de myFunc(data):
    print("before someImportantCall...")
    result = someImportantCall()
    print("after someImportantCall...")

   // your code continues on....

    print("before anotherImportantCall...")
    result = anotherImportantCall()
    print("after anotherImportantCall...")
```

**Comment by dvonthenen** [comment]
Deepgram side of things works just fine. The user is trying to find help with the code they wrote.

I would probably take the problem to Django support and see if they can help with it.
