### ISSUE TITLE
The documentation for the python sdk on the website is completely wrong

### ISSUE THREAD

**Issue by LukasNel** [deepgram/deepgram-python-sdk#236]
https://developers.deepgram.com/docs/getting-started-with-pre-recorded-audio
<img width="892" alt="image" src="https://github.com/deepgram/deepgram-python-sdk/assets/11474572/73fd987f-193e-4f7a-b6d3-ee6c7c7de3df">

This refers to the old one, a fact that isn't mentioned anywhere. Same with the documentation in the api playground.
https://playground.deepgram.com/?smart_format=true&language=en&model=nova-2
<img width="778" alt="image" src="https://github.com/deepgram/deepgram-python-sdk/assets/11474572/1e2a0cea-7548-4130-a630-bd49fe4428ca">
Please update the documentation to use the latest version or pin the version used, this makes the library quite hard to use since the API docs aren't at all consistent.

**Comment by LukasNel** [comment]
In addition, what does "the API in the environment variables mean"? Does that mean that you need to set DEEPGRAM_API_KEY in the enviroment variables? This is specified nowhere.

**Comment by dvonthenen** [comment]
Hi @LukasNel 

Looks like I missed this part of the documentation. I'm fairly new and am still learning where all the documentation lives.

If you look on the main landing page for the Python SDK, that documentation has been updated to the latest along with the beginnings of a migration guide.

You can find that here:
https://developers.deepgram.com/docs/python-sdk

**Comment by LukasNel** [comment]
I don't blame you, I'm just letting you know! This is the type of stuff that turns away devs and you don't want to lose the support of the endusers.

**Comment by LukasNel** [comment]
https://developers.deepgram.com/docs/getting-started-with-live-streaming-audio this one as well is misleading

**Comment by dvonthenen** [comment]
taking a look at it now

**Comment by dvonthenen** [comment]
Separate issue for Playground/Console since the work has been in progress for a couple of weeks.
https://github.com/deepgram/deepgram-python-sdk/issues/237
