### ISSUE TITLE
Quickstart out of date

### ISSUE THREAD

**Issue by mswoff** [deepgram/deepgram-python-sdk#247]
Following the streaming quickstart (and other examples) leads one to use `deepgram = Deepgram(api_key)` which appears to not work. Yields this error `TypeError: Deepgram.__init__() takes 1 positional argument but 2 were given`.

I assume this is because the quick starts are out of date.

**Comment by dvonthenen** [comment]
@mswoff can you paste the link here? I believe all documentation should be up to date, but there are the occasional ones that are off the main workflows that seem to pop up. 

We either need to have these off-the-beaten-path code samples just reference a single source or see if the documentation supports doing an "include" of docs that all pages reference.

**Comment by mxumary** [comment]
Hey! Here's the link: https://colab.research.google.com/drive/1Jall9lHiiVFHwLl2h4kE8EMm4Z2-fUH5#scrollTo=jql62j9YQrai
Also trying something out with Deepgram and encountered the same issue.

**Comment by dvonthenen** [comment]
> https://colab.research.google.com/drive/1Jall9lHiiVFHwLl2h4kE8EMm4Z2-fUH5#scrollTo=jql62j9YQrai

Thanks for providing that link. Yea, that isn't the official documentation so you shouldn't trust/use the contents of that document. I have asked the document owner to either update or delete the document.

Official documentation can be found on the website:
https://developers.deepgram.com/docs/introduction


If you use version `v3.0.1` or later, if you try to create a `Deepgram` object (as the code in that document does), you should immediately receive a fatal error with this message:
```
            FATAL ERROR:
            You are attempting to instantiate a Deepgram object, which is no longer a class in version 3 of this SDK.

            To fix this issue:
                1. You need to revert to the previous version 2 of the SDK: pip install deepgram-sdk==2.12.0
                2. or, update your application's code to use version 3 of this SDK. See the README for more information.

            Things to consider:

                - This Version 3 of the SDK requires Python 3.10 or higher.
                  Older versions (3.9 and lower) of Python are nearing end-of-life: https://devguide.python.org/versions/
                  Understand the risks of using a version of Python nearing EOL.

                - Version 2 of the SDK will receive maintenance updates in the form of security fixes only.
                  No new features will be added to version 2 of the SDK.
```

If you still need help getting started after looking through the docs or the examples (https://github.com/deepgram/deepgram-python-sdk/tree/main/examples), please drop me a line in Discord. If you find a bug, please feel free to file an issue in the repo here.

**Comment by liamsteadman** [comment]
I also experience this issue. The official documentation notebook (on https://developers.deepgram.com/docs/python-sdk) and this page (https://developers.deepgram.com/docs/python-sdk-v2-to-v3-migration-guide) say the deepgram object should be instantiated with an API key, but passing in the API key gives the same error in the original post: `TypeError: Deepgram.__init__() takes 1 positional argument but 2 were given`

**Comment by dvonthenen** [comment]
If you look at the migration guide, there are `before` and `after` tabs in the upper left corner of each code snippet.

The `before` reads:
```
from deepgram import Deepgram

# Your Deepgram API Key
DEEPGRAM_API_KEY = 'YOUR_DEEPGRAM_API_KEY'

# Initialize the Deepgram SDK
deepgram = Deepgram(DEEPGRAM_API_KEY)
```

and the `after` reads:
```
from deepgram import DeepgramClient

# Create a Deepgram client using the API key from environment variables
deepgram = DeepgramClient()
```

**Comment by dvonthenen** [comment]
You aren't the first person to not notice this tab and perhaps we might have gotten a little too clever with using those tabs.
