### ISSUE TITLE
Getting an error when calling the .finish() function

### ISSUE THREAD

**Issue by devashish-gopalani-cognoai** [deepgram/deepgram-python-sdk#254]
## What is the current behavior?

In a particular scenario when I call **deepgram_obj.finish()**, I get the below error.

> received 1000 (OK); then sent 1000 (OK)

Can someone please tell me why this error is coming? Even if someone can give an explanation of the error then that would be great!

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** Ubuntu 20.04.6 LTS
- **Language:** Python SDK version 3.0.0

**Comment by devashish-gopalani-cognoai** [comment]
Hey @dvonthenen,

I am using the sync approach. Also I haven't specified the debug level explicitly still I am getting this log.

**Comment by dvonthenen** [comment]
It's most likely then it's coming from not handling the exception and logging correctly. The error is nothing to worry about though. Just a normal shutdown.

**Comment by dvonthenen** [comment]
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/live/v1/client.py#L194-L198

**Comment by dvonthenen** [comment]
PR merged https://github.com/deepgram/deepgram-python-sdk/pull/256
This should be available in the next release.
