### ISSUE TITLE
Add Start of Speech `vad_events` to Python SDK 

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-python-sdk#260]
see docs for more info: https://developers.deepgram.com/docs/start-of-speech-detection

New API Param: `vad_events`

**Comment by dvonthenen** [comment]
PR merged. Will be available in the next release.

**Comment by jpvajda** [comment]
@dvonthenen will this release be cut this week?

**Comment by dvonthenen** [comment]
this was released yesterday!
