### ISSUE TITLE
Real-time diarization appears in logs but not response

### ISSUE THREAD

**Issue by camberg23** [deepgram/deepgram-python-sdk#265]
Hello, thanks for this amazing python SDK. I am trying to get real-time diarized transcripts for a project I'm working on, but it seems like the response object I'm getting does not include the speaker assignment, while the logs do. Here is the code I'm running (using `deepgram-sdk=3.0.3`):

DEEPGRAM_API_KEY = 'XXXX'
VERBOSE = True

if VERBOSE:
    config = DeepgramClientOptions(verbose=logging.DEBUG, options={"keepalive": "true"})
    deepgram: DeepgramClient = DeepgramClient(DEEPGRAM_API_KEY, config)
else:
    config = DeepgramClientOptions(options={"keepalive": "true"})
    deepgram: DeepgramClient = DeepgramClient(DEEPGRAM_API_KEY, config)

dg_connection = deepgram.listen.live.v("1")

def on_message(self, result, **kwargs):
      sentence = result.channel.alternatives[0].transcript
      if len(sentence) == 0:
          return
      print(result)
      print(f"speaker: {sentence}")

def on_metadata(self, metadata, **kwargs):
      print(f"\n\n{metadata}\n\n")

def on_utterance_end(self, utterance_end, **kwargs):
      print(f"\n\n{utterance_end}\n\n")

def on_error(self, error, **kwargs):
      print(f"\n\n{error}\n\n")

dg_connection.on(LiveTranscriptionEvents.Transcript, on_message)
dg_connection.on(LiveTranscriptionEvents.Metadata, on_metadata)
dg_connection.on(LiveTranscriptionEvents.Error, on_error)

options = LiveOptions(
    punctuate=True,
    diarize=True,
    language="en-US",
    encoding="linear16",
    channels=1,
    sample_rate=16000,
    interim_results=False,
)
print(options)
dg_connection.start(options)

microphone = Microphone(dg_connection.send)

microphone.start()

input("Press Enter to stop recording...\n\n")

microphone.finish()

dg_connection.finish()

print("Finished")

Which leads to the following outputs:

printing `result` (no diarization information):
LiveResultResponse(type='Results', channel_index=[0, 1], duration=2.88, start=0.0, is_final=True, speech_final=True, channel=Channel(alternatives=[Alternative(transcript='This is a test to see if this will work', confidence=0.9941406, words=[Word(word='this', start=0.6776388, end=0.8370833, confidence=0.9921875, punctuated_word='This'), Word(word='is', start=0.8370833, end=0.99652773, confidence=0.9838867, punctuated_word='is'), Word(word='a', start=0.99652773, end=1.2356944, confidence=0.99121094, punctuated_word='a'), Word(word='test', start=1.2356944, end=1.5545833, confidence=0.9941406, punctuated_word='test'), Word(word='to', start=1.5545833, end=1.7140276, confidence=0.9951172, punctuated_word='to'), Word(word='see', start=1.7140276, end=1.8734721, confidence=0.9975586, punctuated_word='see'), Word(word='if', start=1.8734721, end=2.0329165, confidence=0.9970703, punctuated_word='if'), Word(word='this', start=2.0329165, end=2.192361, confidence=0.9946289, punctuated_word='this'), Word(word='will', start=2.192361, end=2.3518054, confidence=0.9375, punctuated_word='will'), Word(word='work', start=2.3518054, end=2.8518054, confidence=0.9926758, punctuated_word='work')])]), metadata=Metadata(request_id='592f5949-852a-4a79-a0ba-7549b02775b8', model_info=ModelInfo(name='general', version='2023-02-22.3', arch='base'), model_uuid='96a295ec-6336-43d5-b1cb-1e48b5e6d9a4'))
speaker: This is a test to see if this will work

Info in logs (diarization information is there):
response_type: Results, data: {'type': 'Results', 'channel_index': [0, 1], 'duration': 2.88, 'start': 0.0, 'is_final': True, 'speech_final': True, 'channel': {'alternatives': [{'transcript': 'This is a test to see if this will work', 'confidence': 0.9941406, 'words': [{'word': 'this', 'start': 0.6776388, 'end': 0.8370833, 'confidence': 0.9921875, 'speaker': 0, 'punctuated_word': 'This'}, {'word': 'is', 'start': 0.8370833, 'end': 0.99652773, 'confidence': 0.9838867, 'speaker': 0, 'punctuated_word': 'is'}, {'word': 'a', 'start': 0.99652773, 'end': 1.2356944, 'confidence': 0.99121094, 'speaker': 0, 'punctuated_word': 'a'}, {'word': 'test', 'start': 1.2356944, 'end': 1.5545833, 'confidence': 0.9941406, 'speaker': 0, 'punctuated_word': 'test'}, {'word': 'to', 'start': 1.5545833, 'end': 1.7140276, 'confidence': 0.9951172, 'speaker': 0, 'punctuated_word': 'to'}, {'word': 'see', 'start': 1.7140276, 'end': 1.8734721, 'confidence': 0.9975586, 'speaker': 0, 'punctuated_word': 'see'}, {'word': 'if', 'start': 1.8734721, 'end': 2.0329165, 'confidence': 0.9970703, 'speaker': 0, 'punctuated_word': 'if'}, {'word': 'this', 'start': 2.0329165, 'end': 2.192361, 'confidence': 0.9946289, 'speaker': 0, 'punctuated_word': 'this'}, {'word': 'will', 'start': 2.192361, 'end': 2.3518054, 'confidence': 0.9375, 'speaker': 0, 'punctuated_word': 'will'}, {'word': 'work', 'start': 2.3518054, 'end': 2.8518054, 'confidence': 0.9926758, 'speaker': 0, 'punctuated_word': 'work'}]}]}, 'metadata': {'request_id': '592f5949-852a-4a79-a0ba-7549b02775b8', 'model_info': {'name': 'general', 'version': '2023-02-22.3', 'arch': 'base'}, 'model_uuid': '96a295ec-6336-43d5-b1cb-1e48b5e6d9a4'}}

Thanks in advance for your help in getting this fixed!

**Comment by dvonthenen** [comment]
Good catch. Looks like I learned something about the `@dataclass` library today. I will have a fix for this in bit. It should make the release on Monday.

**Comment by camberg23** [comment]
Thanks @dvonthenen, much appreciated, I'll give it another try on Monday with the new release to confirm it works on my end before I close the issue 🙂

**Comment by dvonthenen** [comment]
actually @camberg23 can you do a `pip feeeze` and paste the results here? I think that it should be working in the `3.0.3`.

**Comment by dvonthenen** [comment]
I added the same trace and see the speaker results:
```
response_type: Results
response_type: Results, data: {'type': 'Results', 'channel_index': [0, 1], 'duration': 2.64, 'start': 0.0, 'is_final': True, 'speech_final': True, 'channel': {'alternatives': [{'transcript': 'Testing one t three.', 'confidence': 0.9980469, 'words': [{'word': 'testing', 'start': 0.9962121, 'end': 1.3149999, 'confidence': 0.9980469, 'speaker': 0, 'punctuated_word': 'Testing'}, {'word': 'one', 'start': 1.3149999, 'end': 1.474394, 'confidence': 0.9941406, 'speaker': 0, 'punctuated_word': 'one'}, {'word': 't', 'start': 1.474394, 'end': 1.7134848, 'confidence': 0.9550781, 'speaker': 0, 'punctuated_word': 't'}, {'word': 'three', 'start': 1.7134848, 'end': 1.9525757, 'confidence': 0.9980469, 'speaker': 0, 'punctuated_word': 'three.'}]}]}, 'metadata': {'request_id': '591c3033-4f66-416c-b02b-2e38293f0a3e', 'model_info': {'name': 'general', 'version': '2023-02-22.3', 'arch': 'base'}, 'model_uuid': '96a295ec-6336-43d5-b1cb-1e48b5e6d9a4'}}
result: LiveResultResponse(type='Results', channel_index=[0, 1], duration=2.64, start=0.0, is_final=True, speech_final=True, channel=Channel(alternatives=[Alternative(transcript='Testing one t three.', confidence=0.9980469, words=[Word(word='testing', start=0.9962121, end=1.3149999, confidence=0.9980469, punctuated_word='Testing', speaker=0), Word(word='one', start=1.3149999, end=1.474394, confidence=0.9941406, punctuated_word='one', speaker=0), Word(word='t', start=1.474394, end=1.7134848, confidence=0.9550781, punctuated_word='t', speaker=0), Word(word='three', start=1.7134848, end=1.9525757, confidence=0.9980469, punctuated_word='three.', speaker=0)])]), metadata=Metadata(request_id='591c3033-4f66-416c-b02b-2e38293f0a3e', model_info=ModelInfo(name='general', version='2023-02-22.3', arch='base'), model_uuid='96a295ec-6336-43d5-b1cb-1e48b5e6d9a4'))


on_message: LiveResultResponse(type='Results', channel_index=[0, 1], duration=2.64, start=0.0, is_final=True, speech_final=True, channel=Channel(alternatives=[Alternative(transcript='Testing one t three.', confidence=0.9980469, words=[Word(word='testing', start=0.9962121, end=1.3149999, confidence=0.9980469, punctuated_word='Testing', speaker=0), Word(word='one', start=1.3149999, end=1.474394, confidence=0.9941406, punctuated_word='one', speaker=0), Word(word='t', start=1.474394, end=1.7134848, confidence=0.9550781, punctuated_word='t', speaker=0), Word(word='three', start=1.7134848, end=1.9525757, confidence=0.9980469, punctuated_word='three.', speaker=0)])]), metadata=Metadata(request_id='591c3033-4f66-416c-b02b-2e38293f0a3e', model_info=ModelInfo(name='general', version='2023-02-22.3', arch='base'), model_uuid='96a295ec-6336-43d5-b1cb-1e48b5e6d9a4'))


speaker: Testing one t three.
```

**Comment by dvonthenen** [comment]
In `3.0.2`, I believe this is broken and fixed with this PR:
https://github.com/deepgram/deepgram-python-sdk/pull/243

**Comment by camberg23** [comment]
Sure @dvonthenen, here's what I get with pip freeze:

aiohttp==3.9.1
aiosignal==1.3.1
altair==5.2.0
anyio==4.2.0
appnope==0.1.3
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
asyncio==3.4.3
attrs==23.2.0
awscli==1.27.159
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
blinker==1.7.0
botocore==1.29.159
cachetools==5.3.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.4
comm==0.2.1
dataclasses-json==0.6.3
debugpy==1.8.0
decorator==5.1.1
deepgram-sdk==3.0.3
defusedxml==0.7.1
docutils==0.16
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.1
fqdn==1.5.1
frozenlist==1.4.1
gitdb==4.0.11
GitPython==3.1.40
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
importlib-metadata==6.11.0
ipykernel==6.29.0
ipython==8.20.0
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
json5==0.9.14
jsonpointer==2.4
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
jupyter-events==0.9.0
jupyter-lsp==2.2.2
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyter_server==2.12.5
jupyter_server_terminals==0.5.1
jupyterlab==4.0.11
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib-inline==0.1.6
mdurl==0.1.2
mistune==3.0.2
multidict==6.0.4
mypy-extensions==1.0.0
nbclient==0.9.0
nbconvert==7.14.2
nbformat==5.9.2
nest-asyncio==1.5.9
notebook==7.0.6
notebook_shim==0.2.3
numpy==1.26.3
overrides==7.4.0
packaging==23.2
pandas==2.1.4
pandocfilters==1.5.1
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.1.0
prometheus-client==0.19.0
prompt-toolkit==3.0.43
protobuf==4.25.1
psutil==5.9.7
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==14.0.2
PyAudio==0.2.14
pycparser==2.21
pydeck==0.8.1b0
Pygments==2.17.2
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
pytz==2023.3.post1
PyYAML==5.4.1
pyzmq==25.1.2
referencing==0.32.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.0
rpds-py==0.16.2
rsa==4.7.2
s3transfer==0.6.1
Send2Trash==1.8.2
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
streamlit==1.29.0
tenacity==8.2.3
terminado==0.18.0
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
tornado==6.4
traitlets==5.14.1
types-python-dateutil==2.8.19.20240106
typing-inspect==0.9.0
typing_extensions==4.9.0
tzdata==2023.4
tzlocal==5.2
uri-template==1.3.0
urllib3==2.1.0
validators==0.22.0
verboselogs==1.7
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
websockets==12.0
yarl==1.9.4
zipp==3.17.0

**Comment by dvonthenen** [comment]
that is so odd... you should actually see a `speaker: 0` weather you have `diarize` set to True or False.

**Comment by camberg23** [comment]
Looks like something weird is up in my notebook that could be causing the issue, let me sanity check this and get back in a few minutes.

**Comment by camberg23** [comment]
Okay, can confirm it's working on my end now after updating to the latest version. It wasn't immediately working when I updated (in pip freeze above) because I needed to restart the kernel and forgot 🤦‍♂️, I'll go ahead and close the issue. Thanks @dvonthenen

**Comment by dvonthenen** [comment]
no worries!
