### ISSUE TITLE
`keepalive` support only seems to be included in `LiveClient`, but not `AsyncLiveClient`

### ISSUE THREAD

**Issue by tipu** [deepgram/deepgram-python-sdk#272]
## What is the current behavior?

The sync client will start a thread to call ping on the websocket and send the keepalive message. The async client has no support for keepalive at all. I am not sure if this is intentional or not.

## Expected behavior

I would think both clients would support the keepalive configuration option.

**Comment by dvonthenen** [comment]
At the time, it was intentional because the async was on the verge of being removed since the sync/threaded can be used in async code. This isn't a blocker because if you need the keepalive, you can always send them yourself, but we definitely can add it.

**Comment by tipu** [comment]
I was using the async client so I can pass async functions to the `LiveTranscriptionEvents` callbacks. Should I steer away from this if it's planned on being removed?

**Comment by dvonthenen** [comment]
No, it's not being removed. You definitely can still use it and will be supported.

**Comment by tipu** [comment]
Thanks for your help.

**Comment by kormang** [comment]
I also use async client for performance reasons. It is more light weight and the rest of the code is async. I wish it is made in a structured concurrency manner though.

**Comment by dvonthenen** [comment]
Merged PR. Closing Issue.
