### ISSUE TITLE
[Playground] detect_topics not working with transcribe_file

### ISSUE THREAD

**Issue by SantiDianaClibrain** [deepgram/deepgram-python-sdk#280]
The flag detect_topics is set to True in PrerecordedOptions but it is not found in alternatives.

```
with open(filepath, 'rb') as file:
    content = file.read()

payload: FileSource = {
    "buffer": content,
}
try:
        deepgram = DeepgramClient(api_key=DEEPGRAM_API_KEY)

        # STEP 2: Call the transcribe_url method on the prerecorded class
        options = PrerecordedOptions(
            smart_format=True,
            model="nova-2",
            diarize=False,
            language="en",
            punctuate=True,
            detect_entities=True,
            detect_topics=True,
            topics=True,
            summarize=True,
        )
        result = deepgram.listen.prerecorded.v("1").transcribe_file(payload, options)
```

To be able to detect topics:

`topics = result.results.channels[0].alternatives[0].topics[0].topics`

Python SDK

**Comment by dvonthenen** [comment]
Hi @SantiDianaClibrain 

Topics are off the `metadata` object:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/prerecorded/v1/response.py#L533-L534

**Comment by dvonthenen** [comment]
Closing issue since not getting a response. Please reopen if you want to revisit the issue.

**Comment by dvonthenen** [comment]
No, there shouldn't be any need to to manually edit anything.

Can you verify this works for you?
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/prerecorded/topic/main.py

After you run this, can you take note of where the topics are in the result. They are located at:
`topics = result.results.topics`

**Comment by dvonthenen** [comment]
yea, that shouldn't be there. will remove that. thanks for point that out.

**Comment by dvonthenen** [comment]
This update has been submitted for review.
