### ISSUE TITLE
Object of type Sentiment is not JSON serializable

### ISSUE THREAD

**Issue by leddy231** [deepgram/deepgram-python-sdk#296]
## What is the current behavior?

When converting a `PrerecordedResponse` to a dict with `.to_dict()` from dataclasses_json the `Sentiment` enum does not get converted to a string. When later trying to serialize this dict or parts of it after processing the standard python `json` library crashes since `Sentiment` is not JSON serlializable

## Steps to reproduce

```python
from deepgram import PrerecordedOptions, DeepgramClient, UrlSource
import json

client = DeepgramClient()
transcribe = client.listen.prerecorded.v("1")
options = PrerecordedOptions(
    language="en-us",
    model="nova-2",
    tag=["data-automation", "test"],
)
response = transcribe.transcribe_url(
    source=UrlSource(url="https://ia803406.us.archive.org/1/items/HelloWorld/test_64kb.mp3"),
    options=options,
)

response_dict = response.to_dict()

json.dumps(response_dict)
```
```
File ~/.../python/3.10.4/lib/python3.10/json/encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)
...
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type Sentiment is not JSON serializable
```
## Expected behavior

`Sentiment` should either be converted to a string or made serializable. That can easily be done by make it a `str` enum like in this example

```python
from enum import Enum

class MyEnum(str, Enum):
    A = "a"
    B = "b"

print(json.dumps({"a": MyEnum.A, "b": MyEnum.B}))
```
```
{"a": "a", "b": "b"}
```
## Please tell us about your environment

linux
python 3.10.4
deepgram-sdk 3.1.3

## Other information

Im not sure why Sentiment is included at all in this response, im guessing it is because its set as default values in some places. The `PrerecordedOptions` does not request sentiment, so it would make sense that sentiment is not included in the response object in that case

**Comment by dvonthenen** [comment]
Merged PR. Will be available in the next release.
