### ISSUE TITLE
Extra (parameter) results not present in per-message metadata response

### ISSUE THREAD

**Issue by nickottocode** [deepgram/deepgram-python-sdk#318]
## What is the current behavior?

It looks like the extra field comes back within the[ final metadata response](https://github.com/deepgram/deepgram-python-sdk/blob/e832849e7465853da7c4deb20b1ce812c89c7415/deepgram/clients/live/v1/response.py#L164) but not in the [per-message response](https://github.com/deepgram/deepgram-python-sdk/blob/e832849e7465853da7c4deb20b1ce812c89c7415/deepgram/clients/live/v1/response.py#L89)

## Steps to reproduce
https://github.com/deepgram/deepgram-python-sdk/tree/main/examples/streaming/microphone

## Expected behavior
Using raw websockets the metadata includes the extra parameter.  "extra" is included already in the final response.
```sh
"metadata": {"extra": {"example": "param"}, "request_id": "0bbe9f92-5b42-44bc-80cc-7c8f8c891e3f", "model_info": {"name": "general", "version": "2024-01-26.8851", "arch": "base"}, "model_uuid": "1ed36bac-f71c-4f3f-a31f-02fd6525c489"}
```

**Comment by dvonthenen** [comment]
PR merged. Will be cutting a release shortly. Closing issue.
