### ISSUE TITLE
Deepgram audio timeout window error

### ISSUE THREAD

**Issue by devashish-gopalani-cognoai** [deepgram/deepgram-python-sdk#319]
## What is the current behavior?
I have received the below error in my syslog - 
Exception in _listening: received 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001; then sent 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001

When this error occurs, the function which I have added as a callback in the LiveTranscriptionEvents.Error event gets triggered. In this function, I have written the below logic to end the connection with deepgram:

```
self.deepgram_obj.finish()
self.deepgram_obj = None
```

When the .finish() function is executed, I again get the same error - 
received 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001; then sent 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001

My question is, what should be done when we get the 1011 error? How do we close the connection with deepgram gracefully?

We are using deepgram-sdk=3.0.0 and python 3.10
Operating System/Version: Ubuntu 20.04.6 LTS

**Comment by dvonthenen** [comment]
Hi @devashish-gopalani-cognoai 

The 1011 error is letting you know that we aren't receiving any audio data. There is a minimum of 12 seconds in which we need to receive data or Deepgram platform will terminate the connection. You can send a keepalive in order to reset the countdown and buy yourself another 12 seconds.

For the `finish()` error, please update to the latest version of the SDK. We also plan on having a release today that addresses some of the exception-handling issues with the Live Clients.

**Comment by devashish-gopalani-cognoai** [comment]
Hey @dvonthenen,

Thanks for the update. But we do keep sending the keepalive packet in every three seconds and still we end up getting this error. What could be the reason for it?

**Comment by dvonthenen** [comment]
Please retry with the latest posted today:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.1.5

**Comment by devashish-gopalani-cognoai** [comment]
Hey @dvonthenen, the .finish() error did not get resolved after upgrading to v3.1.4. I will try the latest build today. In the meantime, here is the code which we have written to send the keepalive message.

```
deepgram_obj.send(json.dumps({
    'type': 'KeepAlive'
}))

```
Earlier we were sending this every 3 seconds but now I tried sending it every 200-500ms but still I am getting the same error. Here is the detailed stacktrace of the error which we received - 

```
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/deepgram/clients/live/v1/client.py", line 205, in _processing
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     self.send_ping()
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/deepgram/clients/live/v1/client.py", line 252, in send_ping
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     self._socket.ping()
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/websockets/sync/connection.py", line 450, in ping
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     with self.send_context():
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     return next(self.gen)
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/websockets/sync/connection.py", line 724, in send_context
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     raise self.protocol.close_exc from original_exc
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]: websockets.exceptions.ConnectionClosedError: received 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001; then sent 1011 (internal error) Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]: During handling of the above exception, another exception occurred:
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]: Traceback (most recent call last):
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     self.run()
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     self._target(*self._args, **self._kwargs)
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/deepgram/clients/live/v1/client.py", line 219, in _processing
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     self._emit(LiveTranscriptionEvents.Error, error)
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:   File "/home/ubuntu/venv_voicebot/lib/python3.10/site-packages/deepgram/clients/live/v1/client.py", line 100, in _emit
Feb 27 15:49:45 ip-10-102-1-13 daphne[10033]:     handler(self, *args, **kwargs)
```

**Comment by dvonthenen** [comment]
hi @devashish-gopalani-cognoai  the latest is `v3.1.5`. Did you try that one?

**Comment by dvonthenen** [comment]
hi @devashish-gopalani-cognoai 

the 1011 error is from:
1. not receiving any audio data
2. the audio stream encoding doesn't match the `encoding` value

the best way to clean up the client using `v3.1.5`, is to call `finish()` and then set the object to `None`. then create a new client

**Comment by devashish-gopalani-cognoai** [comment]
When you say audio data, you basically mean to say that if no audio data or even if the keepalive packet is not sent for 12 secs, then the 1011 error would come right? 

Regarding clean up - I do call the `finish()` function. But what I have noticed is, when I get a 1011 error for the first time, I see the log of it only once in the syslog. Say if I were to again get the 1011 error for a new connection, ideally the log that should be printed in the syslog should be only one but I get to see two of them. Similarly if I were to again create a new connection and if I were to get the 1011 error again, then the number of logs in the syslog would be 3. Why is this happening? Before creating a new connection each time, I do call the `finish()` function. 

Just FYI - we are using the deepgram-sdk in Django Channel's synchronous consumers.

**Comment by dvonthenen** [comment]
> when you say audio data, you basically mean to say that if no audio data or even if the keepalive packet is not sent for 12 secs, then the 1011 error would come right?

that is correct. if you don't send the keepalive and there is no audio data/stream being sent, you will get a 1011 error.

> But what I have noticed is, when I get a 1011 error for the first time, I see the log of it only once in the syslog. Say if I were to again get the 1011 error for a new connection, ideally the log that should be printed in the syslog should be only one but I get to see two of them.

When you get a 1011, the connection is closed. You shouldn't get any more messages at all. You need to re-create the client at this point.

> Similarly if I were to again create a new connection and if I were to get the 1011 error again, then the number of logs in the syslog would be 3. Why is this happening? Before creating a new connection each time, I do call the finish() function.

This could be a duplicate. I will take a look at that. At that point, consider the client dead.

**Comment by dvonthenen** [comment]
There is a PR here which refactors some of the shutdown socket functionality. If you want to take a look and let me know if this works better for, that would be of big help: https://github.com/deepgram/deepgram-python-sdk/pull/334

**Comment by dvonthenen** [comment]
Take a look at the latest release here as there were improvements in the exception handling on edge cases.
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.1.8

**Comment by devashish-gopalani-cognoai** [comment]
Hey @dvonthenen, I'll have a look. Thanks!

**Comment by devashish-gopalani-cognoai** [comment]
Hey I tried this SDK, when the `finish()` function is called I am getting the following error - `ExoDevWebSocketConsumer.handle_deepgram_close() takes 2 positional arguments but 3 were given`. 

The function signature for the callback function for the "error" event is - 

```
deepgram_connection_obj = deepgram.listen.live.v("1")
options = LiveOptions(model=self.voicebot_config_obj["stt_config"].deepgram_model_name, 
    language=self.voicebot_config_obj["stt_config"].deepgram_language_code,
    interim_results=self.voicebot_config_obj["stt_config"].is_deepgram_interim_results_enabled, 
    endpointing=self.voicebot_config_obj["stt_config"].deepgram_endpointing_value,
    sample_rate=self.voicebot_config_obj["voicebot_config"].exotel_stream_sample_rate,
    encoding=self.voicebot_config_obj["stt_config"].deepgram_encoding_type
    )
deepgram_connection_obj.start(options)
deepgram_connection_obj.on(LiveTranscriptionEvents.Error, self.handle_deepgram_error)

def handle_deepgram_error(self, error, *args, **kwargs):
    try:
        logger.error(f"In handle_deepgram_error - {error}", extra=LOG_EXTRA)
    except Exception as e:
        exc_type, exc_obj, exc_tb = sys.exc_info()
        logger.error("Error in handle_deepgram_error in ExoDevWebSocketConsumer %s at %s", str(
            e), str(exc_tb.tb_lineno), extra=LOG_EXTRA)
```

The error says that the function takes 2 arguments and we are giving 3 arguments but this callback does get successfully triggered. If the definition was not correct then the callback should not have been triggered. Could you please help with this?

**Comment by devashish-gopalani-cognoai** [comment]
Also a bit off topic but when I print the error received in the callback, it prints an object. How can we get the error message?

Here is the error object which gets printed - 
`In handle_deepgram_error - <deepgram.clients.live.v1.client.LiveClient object at 0x7f2ec34dca60> `

**Comment by dvonthenen** [comment]
> Hey I tried this SDK, when the `finish()` function is called I am getting the following error - `ExoDevWebSocketConsumer.handle_deepgram_close() takes 2 positional arguments but 3 were given`.
> 
> The function signature for the callback function for the "error" event is -
> 
> ```
> deepgram_connection_obj = deepgram.listen.live.v("1")
> options = LiveOptions(model=self.voicebot_config_obj["stt_config"].deepgram_model_name, 
>     language=self.voicebot_config_obj["stt_config"].deepgram_language_code,
>     interim_results=self.voicebot_config_obj["stt_config"].is_deepgram_interim_results_enabled, 
>     endpointing=self.voicebot_config_obj["stt_config"].deepgram_endpointing_value,
>     sample_rate=self.voicebot_config_obj["voicebot_config"].exotel_stream_sample_rate,
>     encoding=self.voicebot_config_obj["stt_config"].deepgram_encoding_type
>     )
> deepgram_connection_obj.start(options)
> deepgram_connection_obj.on(LiveTranscriptionEvents.Error, self.handle_deepgram_error)
> 
> def handle_deepgram_error(self, error, *args, **kwargs):
>     try:
>         logger.error(f"In handle_deepgram_error - {error}", extra=LOG_EXTRA)
>     except Exception as e:
>         exc_type, exc_obj, exc_tb = sys.exc_info()
>         logger.error("Error in handle_deepgram_error in ExoDevWebSocketConsumer %s at %s", str(
>             e), str(exc_tb.tb_lineno), extra=LOG_EXTRA)
> ```
> 
> The error says that the function takes 2 arguments and we are giving 3 arguments but this callback does get successfully triggered. If the definition was not correct then the callback should not have been triggered. Could you please help with this?

That's an error in your code that I invite you to try to solve on your own. If you need help, you can always reach out to people in the community on Discord.

**Comment by dvonthenen** [comment]
> Also a bit off topic but when I print the error received in the callback, it prints an object. How can we get the error message?
> 
> Here is the error object which gets printed - `In handle_deepgram_error - <deepgram.clients.live.v1.client.LiveClient object at 0x7f2ec34dca60> `

You can't print the LiveClient since it's an object with moving state.

**Comment by dvonthenen** [comment]
Resolving this issue since we are talking about non-SDK related issues.

**Comment by devashish-gopalani-cognoai** [comment]
Hey @dvonthenen but if this was a code error then the callback also shouldn't have worked right?

**Comment by dvonthenen** [comment]
> Hey @dvonthenen but if this was a code error then the callback also shouldn't have worked right?

No. The `on_close` is only for a clean shutdown. You need to catch any exceptions coming out of your code OR watch for `on_error` messages for abnormal connection termination.
