### ISSUE TITLE
Improved chunking of TTS 

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-python-sdk#343]
## Issue 

* Specifically related to TTS  implementing Chunking is a bit challenging for users.

## Acceptance Criteria

* Chunking by having a native interface for different LLM responses
* Return TTS data as blobs through events when using chunking

**Comment by jpvajda** [comment]
@dvonthenen

**Comment by dvonthenen** [comment]
This issue https://github.com/deepgram/deepgram-python-sdk/issues/420 obsoletes this issue.
