### ISSUE TITLE
Allow `wss://` in the onprem URL.

### ISSUE THREAD

**Issue by jjmaldonis** [deepgram/deepgram-python-sdk#360]
## What is the current behavior?
The Python SDK requires the onprem URL to be `https://...` and if the user tries to set it as `wss://...` because they are using streaming, the connection fails.

## Steps to reproduce
Set the URL to `wss://...` rather than `https://...`. You can use `wss://api.deepgram.com` rather than an onprem URL to reproduce.

## Expected behavior
The `wss` protocol should be accepted, in addition to `https`.

## Please tell us about your environment
Reproducible in any env.

**Comment by dvonthenen** [comment]
You should be able to set the URL to `wss://<your IP or domain>`. If you omit the protocol, the default https is added because the config object doesn't know which API the object is destined for.

Only options would be to:
- create an HTTP and WS specific ClientOptions classes similar to what I did in .NET (this will break compatibility). this explicitly then states which connection you intent to use
- or don't append the `https` and just error out if `http(s)` or `ws(s)` is missing

**Comment by dvonthenen** [comment]
We could do a combination of those options.

- create `DeepgramWsClientOptions` and `DeepgramHttpClientOptions` classes
- keep the older `DeepgramClientOptions` and remove appending `https` to preserve the backwards compatibility

Longer term, this might be more sustainable.

**Comment by jjmaldonis** [comment]
>The reason why I separated the classes out because it implies the options are the same for both REST and WS connections and that it's true. For example, KeepAlive can be set and passed into PreRecorded Client but it doesn't do/mean anything.

I think we're talking about different things here. The [DeepgramClientOptions](https://github.com/deepgram/deepgram-python-sdk/blob/44398e18bc0b449e256033606f3f5db312faa916/deepgram/options.py#L31) class is a higher level class than the streaming/prerecorded configuration classes. I'm pretty sure a short 2-line if statement will work.

**Comment by dvonthenen** [comment]
Yea, we are talking about the same thing. DeepgramClientOptions can be passed into LiveClient and PreRecorded/Speak/Manage/Analyze Clients.

**Comment by dvonthenen** [comment]
Will have something in a bit

**Comment by dvonthenen** [comment]
this slipped my mind... will have something for tomorrow.

**Comment by dvonthenen** [comment]
This fix is available in: https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.2.7
