### ISSUE TITLE
AsyncLive : server rejected websocket connection

### ISSUE THREAD

**Issue by swimleftproducts** [deepgram/deepgram-python-sdk#368]
-- stupid mistake on my end. deleted the post. sorry for posting.

**Comment by swimleftproducts** [comment]
Question on that. Are there asynclive examples somewhere?

**Comment by dvonthenen** [comment]
yup, you can find them in the repo under the `examples` folder:
https://github.com/deepgram/deepgram-python-sdk/tree/main/examples/streaming
