### ISSUE TITLE
Idling transcriber

### ISSUE THREAD

**Issue by bhigy** [deepgram/deepgram-python-sdk#37]
## What is the current behavior?

I try to transcribe some audio with the help of `LiveTranscription` and sometimes, the program idles.

:warning: I am not really transcribing audio live and I think the issue is related to that. I want to test the performance of DG's streaming API on recorded data. What I have been doing so far is sending audio chunks without trying to emulate live timing (I just send them one after the other, i.e. faster than real time).

From what I have seen, the issue might be related to the `LiveTranscription` object not receiving the closing response from the server after sending the finish message. Because I send the data faster than real time, their is quite some gap between the moment when I call the `finish()` method and when the server actually processes it. And this seems to lead to the websocket being closed (I can see this in the debug log) before the client can get/process the closing signal from the server. I am not familiar with websockets so not completely sure here. 

## Steps to reproduce

Try to send recorded audio data **without** waiting between two chunks to simulate real time conditions.

## Expected behavior

Transcription should proceed normally.

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** Ubuntu 22.04
- **Language:** Python

**Comment by shirgoldbird** [comment]
Hi @bhigy! Though we don't suggest streaming files to our real-time API, we did roll out a change last week that should allow the websocket to stay open when this is done. Could you confirm that you're still experiencing this issue and if so, provide the code you're using so we can investigate?

**Comment by bhigy** [comment]
Thanks for the fast reply. I thought this was probably not the intended use. I will try to reproduce the issue and update the code to see if it solves the problem. 

Otherwise, how would you recommend proceeding? Just waiting between each chunk to simulate real time?

**Comment by bhigy** [comment]
Just to be sure, is the change on the client or the server side? I tried again and it didn't idle a single time...

**Comment by shirgoldbird** [comment]
@bhigy The change is on the server side. Glad to hear it's working and you're no longer experiencing this issue! Please feel free to close this out.

That said, we do suggest adding a wait between each chunk to stream in real-time, as you mentioned. This ensures your testing is as close to a real-world streaming application as possible.
