### ISSUE TITLE
Exception: 'LiveClient' object has no attribute 'keep_alive_thread'

### ISSUE THREAD

**Issue by jkroll-deepgram** [deepgram/deepgram-python-sdk#370]
## What is the current behavior?

Customer is reporting an error `'LiveClient' object has no attribute 'keep_alive_thread'` for (on-prem) streaming transcription (I assume this would be an AttributeError but that's not explicitly mentioned in their logs.)

Line: https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/live/v1/client.py#L134

Could this be a threading issue, where the variable is referenced in L134 before it's ready to use from L133?

Minor related log typo: this should read `"keepalive is enabled"`, not `"keepalive is disabled"`: https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/live/v1/client.py#L132

## Steps to reproduce

Streaming with KeepAlive enabled.

## Please tell us about your environment

Using latest Python SDK v3.2.6

**Comment by dvonthenen** [comment]
This fix is available in: https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.2.7
