### ISSUE TITLE
Could not open socket: SpeechStarted

### ISSUE THREAD

**Issue by Dibya069** [deepgram/deepgram-python-sdk#393]
## Microphone accessing for STT
Got the error from this file, `deepgram/deepgram-python-sdk/blob/main/examples/streaming/microphone/main.py`
 New here so, Unable to know what is the mistake, but

- Install all libraries successfully
- Already run other programs from deepgram successfully
- even pre-recorded STT also done 
- Getting the error while doing streaming using microphone
- Only change I did on the code is 
```
DG_API_KEY = os.getenv("DG_API_KEY")
def main():
    try:
        deepgram: DeepgramClient = DeepgramClient(DG_API_KEY)
```

And then I didn't does any changes, Please anybody help me with this !!!

**Comment by Dibya069** [comment]
python 3.10.14

**Comment by dvonthenen** [comment]
You need to update to at least 3.2, but I would update to latest to get any bug fixes.
