### ISSUE TITLE
Diarization + Streaming

### ISSUE THREAD

**Issue by Dibya069** [deepgram/deepgram-python-sdk#399]
### Basically it's not a feature request, I want to know, the way to do diarization on live stream.

- Because, for streaming we need DeepGram latest version
- But for Diarization we need Deepgram==2.12.0 versioin

**Is there any way to do diarization on streaming in real-time ??**

**Comment by dvonthenen** [comment]
I think this should probably be moved to Discord unless there is an issue. The short answer to get the most accurate diarization is to have each speaker on their own audio channel in the audio stream.

If you want more info or discussion, I invite you to join Discord here: 
https://dpgr.am/discord
