### ISSUE TITLE
Inconsistency latency in real time STT with nova-2-phonecall

### ISSUE THREAD

**Issue by wilson97** [deepgram/deepgram-python-sdk#401]
<img width="1384" alt="Screenshot 2024-05-17 at 3 06 03 PM" src="https://github.com/deepgram/deepgram-python-sdk/assets/2347844/0efecb3c-5a9a-4495-bf94-7ae6270df688">

Attached is a graph of the latencies for each speech chunk in live transcription with nova-2-phonecall (including both speech_final true and false). You can see most of the latencies are < 0.5s, which is great, but also sometimes there are spikes above 1s. Since we are using deepgram to make phone calls, anytime the STT latency goes from low to high, it results a lag on our end. Can you guys take a look at this? Is there anything I can do to make sure there is no more latencies above 1s? Thanks.

**Comment by dvonthenen** [comment]
This is the same issue as posted in Discord here:
https://discord.com/channels/1108042150941294664/1241150521348329542

**Comment by dvonthenen** [comment]
This isn't SDK related, but would be happy to discuss in Discord. I cross posted in both just so we don't have someone helping in both places.

**Comment by wilson97** [comment]
Hi @dvonthenen just updated the thread in discord with some more information.
