### ISSUE TITLE
WebSocketException in LiveClient.start: timed out Failed to connect to Deepgram

### ISSUE THREAD

**Issue by Dibya069** [deepgram/deepgram-python-sdk#404]
this error I am getting when ever I tried to run my code for live speech to text transcription.

It's not one time, each and every time it's happening. and recently this is happening very often which is very frustrating.

Please somebody help me to fix this issue.

![image](https://github.com/deepgram/deepgram-python-sdk/assets/121597961/d037c3ba-96fe-4877-b7b3-fea4a79743d7)

**Comment by Dibya069** [comment]
I used virtual audio cable to get the audio from my system for transcription

**Comment by dvonthenen** [comment]
@Dibya069 what region are you in? are you in India by any chance?

We have had an explosion of connectivity issues recently since this issue we are tracking with Tata https://deepgram.gitbook.io/help-center/notices/cogent-tata-peering-issue-impact-on-deepgram

**Comment by Dibya069** [comment]
Yes, I am from India. Ok, then got it
