### ISSUE TITLE
`endpointing` attribute in `LiveOptions` should be a union integer and a generic false.

### ISSUE THREAD

**Issue by digitaldojoai** [deepgram/deepgram-python-sdk#428]
`endpointing` attribute in LiveOptions should be a union integer and a generic false, not a string [[ref](https://developers.deepgram.com/docs/endpointing)]

However in the SDK, it is a string.

`
endpointing: Optional[str] = field(
    default=None, metadata=dataclass_config(exclude=lambda f: f is None)
)`

**Comment by dvonthenen** [comment]
Fixed in this release:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.3.2
