### ISSUE TITLE
Request for Sample Code or sample project: Live Transcription from Microphone

### ISSUE THREAD

**Issue by snehitvaddi** [deepgram/deepgram-python-sdk#440]
I’m currently working on a project that requires live transcription from a microphone. I’ve been searching extensively through the documentation, but I haven’t been able to find a straightforward example or project that demonstrates this functionality.

The closest resource I found is the guide on how to [Transcribe Audio from a Remote Stream](https://cloud.google.com/speech-to-text/docs/samples/speech-transcribe-streaming-mic), but it doesn’t cover live transcription from a microphone.

Could someone please provide or direct me to a sample code or project that demonstrates live transcription from a microphone?

**Comment by dvonthenen** [comment]
Hi @snehitvaddi 

If you search on the readme on the repo for microphone, you should find thr example right there on the readme:
https://github.com/deepgram/deepgram-python-sdk?tab=readme-ov-file#live-audio-transcription-quickstart

If you keep hitting "next", next", etc on the find within the readme, you should do stumble upon the full example in the examples section "Live Audio Transcription: From a Microphone":
https://github.com/deepgram/deepgram-python-sdk?tab=readme-ov-file#examples

**Comment by dvonthenen** [comment]
The 3rd option could also been use the search button at the top of this repo for the term "microphone" which yields this result:
https://github.com/search?q=repo%3Adeepgram%2Fdeepgram-python-sdk%20microphone&type=code
