### ISSUE TITLE
Manual End of Speech

### ISSUE THREAD

**Issue by sidharth72** [deepgram/deepgram-python-sdk#451]
## Proposed changes

I believe it would be beneficial to incorporate a feature in the SDK for detecting a token at the end of speech to ensure accurate end-of-speech detection. This would provide a more reliable way to indicate the end of speech, especially in cases where automatic detection may be imperfect.

**Comment by dvonthenen** [comment]
Hi @sidharth72 

I am not sure if you are aware of these available options:

-`endpointing` - https://developers.deepgram.com/docs/endpointing
- `utternace_end_ms` - https://developers.deepgram.com/docs/understanding-end-of-speech-detection

Those don't meet your needs and If you are proposing something else entirely, could you explain in greater detail what you are looking for? Something closer to a functional spec would be nice. You could drop it right here in this issue.

**Comment by sidharth72** [comment]
Thank You. I just found that it is possible to combine UtteranceEnd and Endpointing to detect End of Speech efficiently.

**Comment by dvonthenen** [comment]
All good! Glad you have a solution!
