### ISSUE TITLE
Error Occurs When Retrieving Usage Information Due to Delay in Data Availability

### ISSUE THREAD

**Issue by Viamo** [deepgram/deepgram-python-sdk#457]
## What is the current behavior?
When calling `deepgram.listen.prerecorded.v('1').transcribe_file(payload, options)` followed immediately by `deepgram.manage.v('1').get_usage_request(DEEPGRAM_PROJECT_ID, requestId)`, an error occurs in the file [`client.py`](https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/manage/v1/client.py) at line 1004. The variable `result` has a value of `None`.

## Steps to reproduce
1. Call `deepgram.listen.prerecorded.v('1').transcribe_file(payload, options)`.
2. Immediately call `deepgram.manage.v('1').get_usage_request(DEEPGRAM_PROJECT_ID, requestId)` with `DEEPGRAM_PROJECT_ID` and `requestId`.

## Expected behavior
The `get_usage_request` function should return valid usage information without returning `None`, and the package should handle the error if the data is not available yet.

## Please tell us about your environment
- **Operating System/Version:** Windows 10
- **Python Version:** v3.11

## Other information
The issue appears to be related to the delay in retrieving usage information. Even if the information is unavailable, the error should still be handled properly by the package.

**Comment by dvonthenen** [comment]
I looked into this, and it is an API issue. I will forward it to engineering, as the API should return an error instead of a result.

In the meantime, I would recommend checking for the `null` value in the result to determine data availability if you have a need for the API that quickly; otherwise, will need to wait for this fix in the API.

**Comment by Viamo** [comment]
The variable `result` is not accessible because it is inside the package. The only way is to give up on the SDK and access the API directly, but for now, I just added `sleep()`.

**Comment by dvonthenen** [comment]
> The variable `result` is not accessible because it is inside the package. The only way is to give up on the SDK and access the API directly, but for now, I just added `sleep()`.

Let me take a look at this and see what I can do.

**Comment by Viamo** [comment]
Thank you for the help. I'm using `sleep()`, and that’s sufficient for now. It would be great if you could address the errors at your end. Thanks!

**Comment by dvonthenen** [comment]
Will be available in the 3.7.0 that is building right now.

**Comment by Viamo** [comment]
It appears that the error is still occurring because, in the file [`client.py`](https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/manage/v1/client.py#L1002), on line 1002, the variable `result` receives a value that may be `None`, and on line 1006, the operation `UsageRequest.from_json(result)` throws an error.
I propose adding a `None` check to ensure that the variable `result` is properly validated before passing it to `UsageRequest.from_json(result)`.

_deepgram-sdk, version: 3.7.3_

**Comment by dvonthenen** [comment]
We just need to mark the field Optional which will set it to None. Will make that change. I also think you mean `response` not `result`, correct?
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/manage/v1/response.py#L489

**Comment by Viamo** [comment]
No, I mean `result` in line 1002. I conducted some investigations and found that sometimes the `result` has a value of `'null'`, which causes an error when calling `res = UsageRequest.from_json('null')`.

![2024-10-17_214427+](https://github.com/user-attachments/assets/c2a3e9a9-f0b5-4f54-beeb-dee9eeb4ff2a)
![2024-10-17_214523](https://github.com/user-attachments/assets/2dbf5c0d-845d-4ff2-9b54-ad444edf2b76)
![2024-10-17_185407](https://github.com/user-attachments/assets/1c950cc3-2438-499d-9d52-679ac3cb720d)

**Comment by Viamo** [comment]
### And one more bug:
Sometimes `usage.response` is `null` in code:
`usage = deepgram.manage.v('1').get_usage_request(DEEPGRAM_PROJECT_ID, request_id)`

### Screenshot for `for i in range(10)`:
There is a difference in the third iteration with the same request.

![2024-10-17_193757+](https://github.com/user-attachments/assets/6234bf4a-d96d-4af4-ae4d-def0c75d45c7)

**Comment by dvonthenen** [comment]
ahhhh I see. My misunderstanding on where the error is. That sounds reasonable.

**Comment by dvonthenen** [comment]
There is a PR open for this. A data availability exception will be thrown now:
- Async: https://github.com/deepgram/deepgram-python-sdk/pull/472/files#diff-409e993c659f805875acecd5f70fc36ddb73ce8b3fbe0bb514882df2a1551fc2R234-R237
- Threaded: https://github.com/deepgram/deepgram-python-sdk/pull/472/files#diff-3fd4f97ff30988310dc483371a310a0eb391e685a5343c24334f625eeebea858R230-R233

**Comment by Viamo** [comment]
Why might the data be unavailable? Is it possible to ensure the data is always available (availability exception is still necessary to implement)? In third-party APIs, usage is returned immediately in the results of the first API call, without requiring a second API call to retrieve usage, which is why their data is always available.

**Comment by dvonthenen** [comment]
I am not sure, but I will pass this along to the API platform team to see if they can address that. Otherwise, if we do receive a `None` value from any of the API calls, we should throw an exception.

**Comment by dvonthenen** [comment]
This should be available in 3.7.4

**Comment by Viamo** [comment]
Hi David! Is this the fix for the error?  
If so, could you double-check to ensure it’s correct? The issue occurs when the received value is not `None`, but `'null'` (as a string), as I mentioned above.

![2024-10-20_151832](https://github.com/user-attachments/assets/aebeb67e-d088-46a7-a0d6-d309d0a443fb)

---

![2024-10-20_153104](https://github.com/user-attachments/assets/67d2d62f-41c0-4076-baf8-4213aa4b766c)

**Comment by Viamo** [comment]
Hi, David! I tested [v3.7.5](https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.7.5) and noticed an odd issue: when making identical `transcribe_file` and `get_usage_request` requests multiple times, the `"usd"` field sometimes has a value of `0.0` in the response. I’ve attached a screenshot 1 showing the differences between
- the request with a correct response (on the left, `"request_id": "f3a3b1db-5557-4f86-8366-ba6e72022feb"`) and
- the request with a defective response (on the right, `"request_id": "35262ffd-b945-4ed5-be3d-c2337312648f"`).

If I repeat the `get_usage_request` request with the same `request_id`, the `"usd"` field then has the correct value (screenshot 2).

In the end, the minimal loop log looks like this:
```
usd = 0.00007
usd = 0.00007
usd = 0.00007
[DeepgramError] DeepgramError: Response is not available yet. Please try again later.
usd = 0.00007
usd = 0.00007
usd = 0.00007
usd = 0
usd = 0.00007
usd = 0.00007
[DeepgramError] DeepgramError: Response is not available yet. Please try again later.
usd = 0.00007
usd = 0.00007
usd = 0
usd = 0.00007
usd = 0.00007
usd = 0.00007
usd = 0.00007
[DeepgramError] DeepgramError: Response is not available yet. Please try again later.
usd = 0.00007
usd = 0.00007
usd = 0.00007
```

Sometimes I get a `DeepgramError`, and sometimes the `"usd"` field is `0`.
As I understand it, the `usage` record doesn't appear immediately but gradually, so sometimes I may not receive the `usage` at all, or receive `usage` without a `response`, or receive `usage` with a `response` but without the `usd` field. I think the issue is with the API.

![2024-10-22_165118+](https://github.com/user-attachments/assets/a983d7b9-b2e1-4925-921f-bda832a36a58)

![2024-10-22_235104+](https://github.com/user-attachments/assets/624c072c-7d17-479a-808c-25a44d0ba6f7)

**Comment by dvonthenen** [comment]
Yea, the behavior is definitely API related since the SDK is only passing things through.

For the times you get 0.0, if you re-query a little later, does it give you the correct value?

**Comment by Viamo** [comment]
> If I repeat the get_usage_request request with the same request_id, the "usd" field then has the correct value (screenshot 2).

**Comment by dvonthenen** [comment]
Yeah, that's the API, and it is probably due to the internal replication of values. In your use case, you need to take note of the value and retry. I can pass this feedback along since this is an API artifact.

**Comment by Viamo** [comment]
Hello! Again this error 😫:

```
[AttributeError] 'NoneType' object has no attribute 'items'
  File "E:\PyProjects3\megogo-tiktok\scripts\s04_transcribe_audio_3_deepgram.py", line 39, in <module>
    transcribe_audio_with_deepgram(time_file_reporter, token_file_reporter)
  File "E:\PyProjects3\megogo-tiktok\scripts\s04_transcribe_audio_3_deepgram.py", line 29, in transcribe_audio_with_deepgram
    transcription_price = get_usage_usd(request_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyProjects3\megogo-tiktok\services\audio_deepgram.py", line 57, in get_usage_usd
    usage = deepgram.manage.v('1').get_usage_request(DEEPGRAM_PROJECT_ID, request_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyProjects3\megogo-tiktok\.venv\Lib\site-packages\deepgram\clients\manage\v1\client.py", line 1006, in get_usage_request
    res = UsageRequest.from_json(result)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyProjects3\megogo-tiktok\.venv\Lib\site-packages\dataclasses_json\api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyProjects3\megogo-tiktok\.venv\Lib\site-packages\dataclasses_json\api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyProjects3\megogo-tiktok\.venv\Lib\site-packages\dataclasses_json\core.py", line 163, in _decode_dataclass
    kvs = {decode_names.get(k, k): v for k, v in kvs.items()}
                                                 ^^^^^^^^^
```

**Comment by Viamo** [comment]
The issue is still not resolved.  
Previously, the error was `[AttributeError] 'NoneType' object has no attribute 'items'`. Now, in the latest version of `deepgram-sdk`, it has changed to `[AttributeError] 'NoneType' object has no attribute 'get'`.

**Comment by Viamo** [comment]
We are considering switching to another service, `AssemblyAI`, because you are unable to resolve this issue.
