### ISSUE TITLE
`TypeError Due to Unexpected Keyword Argument in `PrerecordedOptions` Initialization`

### ISSUE THREAD

**Issue by Viamo** [deepgram/deepgram-python-sdk#459]
## What is the current behavior?
In the code snippet:
```python
from deepgram import PrerecordedOptions

# It's working
print('Case 1')
options = PrerecordedOptions()
options.custom_topic = '...'

# It's not working
print('Case 2')
options = PrerecordedOptions(custom_topic = '...')
```
`Case 1` works as expected, but `Case 2` raises a `TypeError` because `PrerecordedOptions.__init__()` received an unexpected keyword argument 'custom_topic'.

## Steps to reproduce
1. Import `PrerecordedOptions` from the `deepgram` module.
2. Execute `Case 1` where `custom_topic` is set as an attribute after instantiation.
3. Execute `Case 2` where `custom_topic` is passed as a keyword argument during instantiation.

## Expected behavior
`PrerecordedOptions` should accept `custom_topic` as a keyword argument during instantiation, or the attribute should be set correctly after instantiation.

## Please tell us about your environment
- **Operating System/Version:** Windows 10
- **Python Version:** v3.11

## Other information
It appears that `PrerecordedOptions` does not support setting `custom_topic` via a keyword argument during initialization, but allows setting it as an attribute after instantiation.

**Comment by dvonthenen** [comment]
Will have a fix for this. The name of the property is plural when it should be singular.

**Comment by Viamo** [comment]
And please improve the [documentation](https://developers.deepgram.com/docs/topic-detection), as it is currently insufficient. Clarify why `custom_topic` is a string and explain how to configure up to 100 topics.

**Comment by Viamo** [comment]
And please demonstrate how to use `custom_topic` and `custom_topic_mode` in the [main.py](https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/speech-to-text/rest/topic/main.py) example script.

**Comment by dvonthenen** [comment]
Available in this release:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.5.2

**Comment by Viamo** [comment]
Thank you. I'll review the release tomorrow. Additionally, please enhance the [documentation](https://developers.deepgram.com/docs/topic-detection) as it currently lacks detail. Specifically, clarify why `custom_topic` is a string and explain how to configure up to 100 topics.
Also, demonstrate how to use `custom_topic` and `custom_topic_mode` in the [main.py](https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/speech-to-text/rest/topic/main.py) example script.

**Comment by dvonthenen** [comment]
hi @Viamo 

That was an oversight/bug... As you can see now, it takes a string or a list of strings.
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/listen/v1/rest/options.py#L44

It should be pretty evident now how to use it, but will update the docs for topics, intents, etc both in prerecorded and in analyze/read to explicitly state you supply multiple instances of the parameter.
