### ISSUE TITLE
DeepgramApiError is not in the python SDK

### ISSUE THREAD

**Issue by ayhuang** [deepgram/deepgram-python-sdk#461]
## What is the current behavior?
I am trying to implement error handling in our code that invokes the python SDK  function deepgram.listen.rest.v("1").transcribe_url_callback().  I am getting a DeepgramApiError exception. But I can't find that on the list of errors in the SDK (v3.4) source, and no documentation anywhere either.  How am i supposed to catch that?

## Steps to reproduce
use a bogus API key

## Please tell us about your environment
aws lambda, Python 3.12 deepgram 3,4

**Comment by dvonthenen** [comment]
Available in this release:
