### ISSUE TITLE
paragraphs missing in alternatives in 3.70

### ISSUE THREAD

**Issue by tevslin** [deepgram/deepgram-python-sdk#466]

**Comment by dvonthenen** [comment]
Hi @tevslin 

I am looking into this.

**Comment by dvonthenen** [comment]
Hi @tevslin 

I am testing the fix right now. In the meantime, I forgot to mention that you can rollback to 3.6 if it is urgent.

**Comment by tevslin** [comment]
Thank you.

 

Just for interest, I was going crazy because my code worked in Spyder but not in Docker. The AI bot on the Deepgram site suggested I check for version incompatibilities and, sure enough, I built the Spyder env a week or so ago and Docker was pulling the latest. Look forward to the fix and will drop back if I need to.

**Comment by tevslin** [comment]
Have installed 3.7,1 from pypi and can verify that it corrects the problem which cropped up in 3.7.0. Thank you.

**Comment by dvonthenen** [comment]
Thanks for confirming! I really appreciate it!
