### ISSUE TITLE
Clear message fails due to accessing undefined "meta_result" variable

### ISSUE THREAD

**Issue by meralan** [deepgram/deepgram-python-sdk#476]
## What is the current behavior?
You get an exception when you send clear message due to accessing an undefined variable while logging.

Exception:
```
 "description": "Exception in AsyncSpeakWebSocketClient._process_text",
 "message": "cannot access local variable 'meta_result' where it is not associated with a value",
```

problematic line in Async Client [here](https://github.com/deepgram/deepgram-python-sdk/blob/433e6f29a88fac385644b7dab5aa5aa771e74382/deepgram/clients/speak/v1/websocket/async_client.py#L331).
```python
case SpeakWebSocketEvents.Cleared:
  clear_result: ClearedResponse = ClearedResponse.from_json(message)
  self._logger.verbose("ClearedResponse: %s", meta_result)
  await self._emit(
      SpeakWebSocketEvents(SpeakWebSocketEvents.Cleared),
      cleared=clear_result,
      **dict(cast(Dict[Any, Any], self._kwargs)),
```

problematic line in Client [here](https://github.com/deepgram/deepgram-python-sdk/blob/433e6f29a88fac385644b7dab5aa5aa771e74382/deepgram/clients/speak/v1/websocket/client.py#L329)
```python
 case SpeakWebSocketEvents.Cleared:
    clear_result: ClearedResponse = ClearedResponse.from_json(message)
    self._logger.verbose("ClearedResponse: %s", meta_result)
    self._emit(
        SpeakWebSocketEvents(SpeakWebSocketEvents.Cleared),
        cleared=clear_result,
        **dict(cast(Dict[Any, Any], self._kwargs)),
``` 

## Expected behavior
```python
...
clear_result: ClearedResponse = ClearedResponse.from_json(message)
self._logger.verbose("ClearedResponse: %s", clear_result)
...
```

**Comment by dvonthenen** [comment]
Hi @meralan 

Will provide an update on Monday unless you want to submit a PR for it.

**Comment by meralan** [comment]
@dvonthenen easy enough change so happy to submit as soon as i have the permission.
