### ISSUE TITLE
Add the PyTest Testing Framework to the Python SDK

### ISSUE THREAD

**Issue by geekchick** [deepgram/deepgram-python-sdk#54]
## Proposed changes

> Add the PyTest testing tool to the Python SDK. Once it's added write a test for the the `PrerecordedTranscription` class and the `async def prerecorded` function inside the `Transcription` class, in the `transcription.py` file. Make sure your tests run and pass locally before committing them. When all your tests pass, please do a pull request and assign @geekchick as a reviewer.

## Context

> Currently, the Python SDK doesn't have any tests, and these are important. Adding PyTest would be an appreciated contribution so we can have test coverage. This would allow developers using the Python SDK to have a better experience as well as to help our Deepgram developers catch defects before releasing to production. 

> Why is this change important to you? How would you use it? How can it benefit other users?

This change is significant because we can finally have test coverage.

**Comment by sudiptog81** [comment]
Working on this!
