### ISSUE TITLE
Exception: DG: server rejected WebSocket connection: HTTP 401 (OS:MAC)

### ISSUE THREAD

**Issue by akjoshi009** [deepgram/deepgram-python-sdk#69]
import pyaudio
from deepgram import Deepgram
import deepgram

client = Deepgram("api key")

# Set the sample rate and chunk size for the audio stream
SAMPLE_RATE = 16000
CHUNK_SIZE = 1024

# Create a new PyAudio object
audio = pyaudio.PyAudio()
audio.get_device_info_by_index(0)

# Open the audio stream using PyAudio
stream = audio.open(
    format=pyaudio.paInt16,
    channels=1,
    rate=SAMPLE_RATE,
    input=True,
    frames_per_buffer=CHUNK_SIZE
)

async def getaudiotranscript(data):
          deepgramLive = await client.transcription.live({'punctuate': True, 'interim_results': False})    
          deepgramLive.registerHandler(deepgramLive.event.CLOSE, lambda c: print(f'Connection closed with code {c}.'))
          deepgramLive.send(data)
          result = client.transcription(data)
          print(result.text)
          

# Loop until the user stops the program
while True:
    # Read a chunk of audio from the stream
    data = stream.read(CHUNK_SIZE)
    
    # Send the audio chunk to Deepgram for recognition
    reposnse = await getaudiotranscript(data)

    

    # Print the recognized text to the console
    

# Close the audio stream
stream.close()

**Comment by dvonthenen** [comment]
The live websocket client is getting reworked currently. Will check back when finished.

**Comment by dvonthenen** [comment]
A new release was just posted which should address this problem, please take a look:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.0.0-alpha.1
