### ISSUE TITLE
Static Type Checking via mypy - PEP 561 support

### ISSUE THREAD

**Issue by seanhess** [deepgram/deepgram-python-sdk#78]
## Proposed changes

I'm new to python so excuse me if I'm missing something obvious. 

You've carefully added type hints to the SDK, amazing. When I add a static type checker to my project, like mypy, it can't seem to find them. According to mypy's documentation, packages are supposed to declare their compatibility with a py.typed file in the package directory. See here: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

## Context

Static type checking dramatically reduces developer errors. You've already created types, adding compatibility to PEP 561 would allow us to use static checkers

## Possible Implementation

See above

## Other information

Am I missing anything? Another way to run a static type checker perhaps?

**Comment by jpvajda** [comment]
👋  This is probably better posted in our [Community Forum](https://github.com/orgs/deepgram/discussions) as it doesn't sound like an issue with the SDK. if it's still an issue for you feel free to post there and a Community member can assist.

**Comment by npip99** [comment]
Any update on this? Not sure why it wouldn't be a GitHub issue here, seems similar to e.g. a form of documentation (#304)

**Comment by dvonthenen** [comment]
I'm actually looking into something for our CI system actually this week. I'm evaluating a bunch of different options at the moment and this is one of them.
